= Antora CLI

== What's the Antora CLI?

The Antora command line interface (Antora CLI) helps you configure and run Antora, its software components, and any applicable libraries and extensions.
When the Antora CLI is installed, you can interact with Antora from the command prompt of your terminal application.

TIP: If you aren't familiar with CLIs, the xref:primer.adoc[] provides a basic overview of command line functions and terminal application concepts.

[#cli-commands]
== Base and generate commands

The Antora CLI provides access to two commands.

[cols="1,2",width=80%]
|===
|Command |Purpose

|`antora`
|Required base command that calls Antora.

|`generate`
|The command generates a site using the specified playbook file.
A playbook file is required in the function's argument.
`generate` executes by default.
|===

[#run-cli-commands]
== Run the antora and generate commands

At its simplest, a command line function explicitly specifies the required `antora` command and required playbook argument.
If the function in <<ex-simple>> is executed from the Antora CLI, Antora will generate a site using a playbook file named [.path]_antora-playbook.yml_.

[#ex-simple]
.antora base command and playbook argument
----
$ antora antora-playbook.yml
----

Let's break down the function in <<ex-simple>>.

The function starts with the `antora` command.
This calls Antora to run the remaining command and argument.
The remaining command is `generate`.
You don't need to explicitly specify it because it's run by default.
But it does require an explicit argument that specifies the filesystem path of a xref:playbook:index.adoc[playbook file] relative to the xref:primer.adoc#working-directory[working directory].
In <<ex-simple>>, the relative filesystem path to the playbook file is [.path]_antora-playbook.yml_.

If you wanted to explicitly specify the `generate` command the function would look like <<ex-explicit>>.

[#ex-explicit]
.Explicitly run the generate command
----
$ antora generate antora-playbook.yml
----

The commands and argument shown in <<ex-explicit>> are equivalent to those in <<ex-simple>>.
You can see more examples of the `antora` and `generate` commands in xref:ROOT:run-antora.adoc#run-antora[Run Antora].

[#specify-playbook]
== Specify a playbook

The file extension of the playbook doesn't need to be specified.
Antora auto-detects the file extension as long as the playbook argument is a file's stem (e.g., [.path]_local-antora-playbook_, [.path]_antora-playbook_, etc.)
The playbook argument in <<ex-detect>> doesn't have a file extension, so Antora will look for a file matching the playbook's file stem name.

[#ex-detect]
.Auto-detection of the playbook file extension
----
$ antora local-antora-playbook
----

Antora's search order for unspecified playbook file formats is YAML, then JSON, and then TOML.

[#cli-help]
== Display the Antora CLI help

The `antora` and `generate` commands xref:options.adoc[accept options].
The option that both of these commands share is `-h` or `--help` which displays help in your terminal for the Antora CLI commands and their options.

The function in <<ex-base-help>> will display help for the `antora` command.

[#ex-base-help]
.Display help for the antora command
----
$ antora -h
----

Help can also be displayed for the `generate` command.

.Display help for the generate command
----
$ antora generate --help
----
