'use strict'

/**
 * Site Publisher component for Antora
 *
 * Publishes the files generated by the Antora generator to the destination(s)
 * specified in the playbook.
 *
 * @namespace site-publisher
 */
module.exports = require('./publish-site')
