= Attachments Directory and Files

[#attachments-dir]
== Attachments family directory

A module directory can contain an xref:family-directories.adoc[optional family directory] named [.path]_attachments_.

[listing]
----
📂 modules
  📂 ROOT
    📂 attachments <.>
      📄 an-attachment.zip <.>
    📂 pages
      📄 a-source-file.adoc
    📄 nav.adoc
----
<.> An [.path]_attachments_ family directory in a [.path]_ROOT_ module directory
<.> An attachment file

Antora applies preset behavior to the files stored in an [.path]_attachments_ directory when it generates a site.

[#attachments]
== Attachment files

Attachment files, or attachments for short, are resources, such as PDFs or the ZIP archives of sample projects.
Attachment files are stored in an [.path]_attachments_ directory.
Regardless of the component version the attachment is assigned to, an xref:page:attachments.adoc[attachment can be cross referenced] by any page, resource, or navigation file.

Antora automatically publishes each attachment, except when the attachment file is marked as xref:standard-directories.adoc#hidden-files[hidden or it's missing a file extension].
Antora uses the xref:how-antora-builds-urls.adoc#family[family segment] and xref:how-antora-builds-urls.adoc#relative-path[relative path segment of the attachment file] when building the URL for an attachment.

=== Binaries and other large files

If your content includes large attachment files, such as sample project binaries, libraries, or PDFs, we don't recommend storing them in a regular git repository.
Instead, host them in a binary repository such as Bintray or S3, or use git LFS (Large File Storage).

include::partial$assets-directory.adoc[]
