= Select a Start Page
:listing-caption: Example
:xrefstyle: short

== Default start page

By default, Antora looks for a page named [.path]_index.adoc_ in the ROOT module of a component version and uses it as the component version's start page (e.g., _\https://site-url.org/component-name/version/index.html_).
If Antora doesn't find this page, site visitors are directed to a 404 page every time they click on that component version from the xref:navigation:index.adoc#component-dropdown[component version selector].

Antora won't look for [.path]_index.adoc_ in the ROOT module when the <<start-page-key,start_page key>> is set in a component version's [.path]_antora.yml_.
Instead, the page assigned to `start_page` will be used as the component version's start page.

[#start-page-key]
== start_page key

The `start_page` key must be set in [.path]_antora.yml_ when:

. a component version doesn't have a page named [.path]_index.adoc_ in its ROOT module, or
. when Antora should use a an alternate page (that is, not [.path]_index.adoc_, even if it exists) as the component version's start page.

`start_page` accepts a xref:page:page-id.adoc[page ID] that points to a page in the component version.
The page ID must specify a module coordinate.

[#ex-start]
.antora.yml
[source,yaml]
----
name: colorado
title: Colorado ∆
version: '5.6'
start_page: get-started:overview.adoc
----

In <<ex-start>>, the component version's start page, `overview.adoc`, is located in the module `get-started`.
