= What's a Component Version?

== Component version

A [.term]*component version* typically represents a discreet and unique version of the documentation for a single product, library, project, microservice, or training course.
Antora can identify all of a component version's source files, regardless of where the files are stored and collected from, because they're associated with the same xref:component-name-and-version.adoc#name-key[component name] and xref:component-name-and-version.adoc#version-key[component version].
A xref:component-version-descriptor.adoc[file named _antora.yml_] is responsible for defining the component version and applying the specified configuration to the component version's source files.
//Source files are associated with a component version by the existence of a file named , which is located in a parent directory.

[#component-version-vs-docs-component]
== What's the difference between a component version and a docs component?

The term [.term]*documentation component*, also known as a *docs component* or *component*, is used when a concept or action applies to all of the component versions that have the xref:component-name-and-version.adoc#name-key[same component name].
////
However, when it comes to producing your documentation site, Antora classifies source files by component version.
It doesn't recognize files solely by component name, and therefore it doesn't apply metadata and attributes, sort and process files, or display pages solely by component name (even though it may look like it does in some cases).
////

[#docs-component-vs-site]
== What's the difference between a docs component and a site?

A [.term]*documentation site* or *site* is a website generated by Antora and published to directory or domain specified in a playbook.
A site consists of one or more docs components and each docs component consists of one or more component versions.
