= Define a Component Version with antora.yml
//:listing-caption: Example
//:xrefstyle: short
:note-caption: ASSUMPTIONS

[NOTE]
====
You understand what a xref:component-version.adoc[component version] is and the purpose of xref:component-version-descriptor.adoc[_antora.yml_].
====

On this page, you'll learn:

* [x] The requirements an [.path]_antora.yml_ file must meet.
* [x] How to assign a valid value to the `name` key.
* [x] How to assign a valid value to the `version` key.
* [x] How to enter keys and values in an [.path]_antora.yml_ file.

[#requirements]
== antora.yml requirements

The component version descriptor file must:

* be named [.path]_antora.yml_
* be written in valid YAML
* contain the `name` key and its value
* contain the `version` key and its value
* be stored xref:component-structure.adoc#overview[at the same directory level as the _modules_ directory]

[#name-key]
== name key

A component name is assigned in [.path]_antora.yml_ using the `name` key.
The `name` key is required.
The `name` typically represents the name of your project, library, or course (e.g., `fauna`, `rudder`, `nrepl`).

.antora.yml with defined component name
[source,yaml]
----
name: colorado
----

The value can contain letters, numbers, underscores (`+_+`), hyphens (`-`), and periods (`.`).
The value *cannot* contain spaces.

TIP: To minimize the likelihood of portability issues between web servers, letters used in the `name` key's value should be lowercase.

Antora uses the `name` key when interpreting page and resource IDs and generating the URLs for the component version's pages.
It also uses `name` where ever the component's name is displayed in the reference UI unless the xref:component-title.adoc[title key is set].
The reference UI shows the component name in the xref:navigation:index.adoc#component-menu[component navigation menu], xref:navigation:index.adoc#component-dropdown[component version selector], and
the first breadcrumb position on a component version's pages.

[#version-key]
== version key

A version, such as an identifier (e.g., `master`, `stable`), code name (e.g., `jesse`), or number (e.g., `1.0`), is assigned to the `version` key in [.path]_antora.yml_.
The `version` key is required.
The `version` key is used as the version coordinate in page and resource IDs and as the version segment in page URLs.
It's used to xref:component-versions.adoc[sort component versions that have the same name by descending version order] in the reference UI.
When the optional `display_version` key isn't set, the value of `version` is shown in the reference UI's xref:navigation:index.adoc#component-menu[component navigation menu], xref:navigation:index.adoc#component-dropdown[component version selector], and xref:navigation:index.adoc#page-dropdown[page version selector].

.antora.yml with defined component version
[source,yaml]
----
name: colorado
version: '5.6'
----

The value can contain letters, numbers, periods (`.`), underscores (`+_+`), and hyphens (`-`) (e.g., `2.8`, `rawhide`)
If the value starts with a number, YAML recommends that it be enclosed in a set of single quote marks (`'`).
The value *cannot* contain spaces.

TIP: To minimize the likelihood of portability issues between web servers, letters used in the `version` key's value should be lowercase.

The `version` key isn't related, though it may be similar, to the xref:component-versions.adoc[name of the branch, tag, or directory] where the component version's source files are stored.
See xref:component-versions.adoc#setting-the-version-for-a-branch[Setting the version for a branch] for more examples and xref:component-versions.adoc#versionless-components[Versionless components] to learn how to create a versionless component.

[#assign-name-and-version]
== Assign a name and version to a component version

Let's create an [.path]_antora.yml_ file that defines the name and version of a component version.
In this exercise, we'll create a component version for the project _Silver Leaf_.
Its component name will be _silver-leaf_, and its version will be _7.1_.

. Open a new file in the text editor or IDE of your choice.
. On the first line, type `name`, directly followed by a colon (`:`).
. Insert a blank space after the colon, and then type the value you want to assign to `name`.
+
[source,yaml]
----
name: silver-leaf
----

. At the end of the value, press kbd:[Enter] to go to the next line.
. Type `version`, directly followed by a colon (`:`), and then a blank space.
. Type the value you want to assign to `version`.
In this example, the value is enclosed in a set of single quote marks (`'`) because it starts with a number.
+
[source,yaml]
----
name: silver-leaf
version: '7.1'
----

. Save the file as [.path]_antora.yml_ in the parent directory that contains the directories and files you want to assign to this component version.
That is, it should be located adjacent to the [.path]_modules_ directory.

You've now associated a set of source files with a component version!
When Antora runs, all of the subsequent subdirectories and source files will be assigned the component name `silver-leaf` and the version `7.1`.
These values will also be used as page and resource ID coordinates and in the URLs of the pages generated from the component version's source files.

[#optional-keys]
== Optional antora.yml keys

You can assign additional metadata, designate a component version as a prerelease, apply AsciiDoc attributes, and register a component version's navigation list and start page using the component version descriptor.

[cols="1,3"]
|===
|Key |Description

|xref:component-attributes.adoc[asciidoc]
|Accepts the `attributes` key and its nested list of `key: value` pairs.

|xref:component-attributes.adoc[attributes]
|Requires the `asciidoc` key.
Accepts a nested list of `key: value` pairs that represent AsciiDoc attributes (e.g., `idseparator: '-'`, `page-level: Advanced`)
Attributes that are set or unset in [.path]_antora.yml_ are applied to all of the pages and resources (where applicable) in a component version.

|xref:component-display-version.adoc[display_version]
|Alternate version displayed in the reference UI's component navigation menu, component version selector, and page version selector.
When `display_version` isn't set, the reference UI falls back to `version`.
`display_version` can accept empty spaces, uppercase letters, and most characters (e.g., `3.0 Beta`, `RED WREN!`).

|xref:component-navigation.adoc[nav]
|List of navigation files Antora uses to build the component version's navigation menu.
Navigation files (e.g., [.path]_nav.adoc_) that aren't registered under the `nav` key will not be used in the component version's navigation menu.

|xref:component-prerelease.adoc[prerelease]
|Designates the component version as a prerelease version.
Antora applies alternate sorting and routing rules to component versions marked as prereleases.
Key can be used to append a prerelease label (e.g., Beta, alpha.2) to `version` without affecting the version coordinate or version URL segment.

|xref:component-start-page.adoc[start_page]
|Specifies that the page corresponding to the assigned page ID is the component version's home page.
By default, Antora uses the [.path]_index.adoc_ file in a component version's ROOT module if `start_page` isn't set.

|xref:component-title.adoc[title]
|Alternate component name displayed in the reference UI's component navigation menu, component version selector, and page breadcrumbs.
The `title` key can accept empty spaces, uppercase letters, and a broader range of characters (e.g., `SUSE Manager`, `APIkit`).
|===

////
.antora.yml
[#ex-1]
[source,yaml]
----
name: name-of-component
title: The title of the component used for display in the UI
version: name-of-version
start_page: name-of-a-module:filename.adoc
nav:
- modules/name-of-a-module/nav.adoc
- modules/ROOT/nav.adoc
----

The <<name-key>> and <<version-key>> keys are always required.
The <<title>>, <<display-version>>, <<start-page-key>>, and <<nav-key>> keys may be optional depending on the version name, structure, and file names associated with a documentation component.
////
