= What's a Component Version?

== Component version

A [.term]*component version* typically represents a discreet and unique version of the documentation for a project, library, service, or training course.
Antora collates all of a component version's source files, regardless of where the files are stored and collected from, that are associated with the same xref:component-name-and-version.adoc#name-key[component name] and xref:component-name-and-version.adoc#version-key[component version].
A xref:component-version-descriptor.adoc[file named _antora.yml_] is responsible for marking the location of a set of source files that belong to a component version, defining the component version, and applying the specified configuration to the component version's source files.

[#component-version-vs-docs-component]
== What's the difference between a component version and a docs component?

The term [.term]*docs component*, also known as a *documentation component* or simply *component*, is used when a concept or action applies to all of the component versions that have the xref:component-name-and-version.adoc#name-key[same component name].

////
move to better location

[#docs-component-vs-site]
== What's the difference between a docs component and a site?

A [.term]*documentation site* or *site* is a website generated by Antora and published to a directory or domain specified in a playbook.
A site typically consists of one or more docs components and each docs component consists of one or more component versions.
////
