= What's antora.yml?
:page-aliases: component-descriptor.adoc
//When Antora receives instructions from a playbook to scan a content source repository, its first objective is to find a component version descriptor file named _antora.yml_ in that repository.
//This file marks the subsequent directories and files as part of a component version and classifies the files according to the component name, component version, and other stable metadata it provides.

== Component version marker and descriptor

The component version descriptor is a configuration file named [.path]_antora.yml_.
It has two crucial functions:

. [.path]_antora.yml_ marks the location of a set of directories and source files that belong to a component version.
. [.path]_antora.yml_ provides required and optional component version metadata that Antora assigns to the source files it collects from the marked location.

[#marker]
== How does Antora use an antora.yml file to find a component version's source files?

A xref:playbook:index.adoc[playbook] tells Antora what xref:playbook:configure-content-sources.adoc[remote repositories and local content sources] it should fetch.
Then, starting at each content source root, Antora looks for an [.path]_antora.yml_ file.
If it finds [.path]_antora.yml_, it searches for a  xref:module-directories.adoc[sibling _modules_ directory] and considers all of the [.path]_modules_ directory's xref:standard-directories.adoc[subdirectories and files] to be part of a xref:component-version.adoc[component version].

This ability to store the source files of a component version anywhere in a directory hierarchy, as long as the parent directory contains an [.path]_antora.yml_ file, allows you to maintain and manage a component version (or part of a component version) in a repository with the software it documents, a sample project, or in its own repository.

[#metadata-configuration]
== What component version information does antora.yml provide?

The [.path]_antora.yml_ file is referred to as the [.term]*component version descriptor* because it provides required and optional information that identifies, describes, and configures a xref:component-version.adoc[component version].
In turn, this metadata and configuration is applied to all of the source files that belong to the component version.

This is why Antora can collect files from multiple repositories, directories, branches, and tags and compile them into a component version.
Antora doesn't process files based on their file system or repository location.
Instead, Antora classifies and converts files based on the information assigned to the source files by a component version descriptor file.

An [.path]_antora.yml_ file contains the following required keys:

include::partial$required-component-version-keys.adoc[]

An [.path]_antora.yml_ file can also contain any of the following optional keys:

include::partial$optional-component-version-keys.adoc[]
