= Define a Component Version with No Version

Sometimes the project or process you're documenting isn't versioned.
For example, hosted technology services and team handbooks may only need their content to represent how the service or process works as of right now.
This is where the reserved version value of a tilde, `~`, comes into play.

== Assign ~ to the version key

To define a component version that doesn't have a version, assign a tilde, `~`, to the `version` key.
The `~` is shorthand for the value `null`, which also specifies a versionless component version when assign to the `version` key.

.antora.yml for a versionless component version
[source,yaml]
----
name: component-name
version: ~ # <.>
----
<.> On a new line, type the key `version`, directly followed by a colon and a blank space (`++: ++`).
Then enter the value `~`.

Antora doesn't apply the same behavior and output rules to an unversioned component version that it does to a component version with a named or semantic version.
For example, Antora doesn't include the version segment in the page and asset URLs of an unversioned component version (e.g., [.path]_/component-name/module-name/page-name.html_).

[#usage]
== Behavior and output

Every component version has a value assigned to its `version` key because Antora applies a default set of behavior and output rules to a xref:component-version-key.adoc#usage[component version based on the value assigned to the version key].
Antora uses a modified set of these rules when processing an unversioned component version.
When the `version` key is assigned `~`, defining the component version as unversioned, Antora:

* sorts the unversioned component version above xref:how-component-versions-are-sorted.adoc[other versions that belong to the same component]
* identifies it as the xref:how-component-versions-are-sorted.adoc#latest-version[latest version of a component] or, if the `prerelease` key is set, as the latest prerelease version of a component
* assigns the fallback value `default` to the `display_version` key at runtime for display purposes in the UI menus, except when:
** the `display_version` key is assigned a value in [.path]_antora.yml_, or
** the xref:component-prerelease.adoc#identifier[prerelease key is assigned an identifier] and the `display_version` key isn't set in [.path]_antora.yml_; at runtime, Antora assigns the identifier to the `display_version` key
* doesn't add a xref:how-antora-builds-urls.adoc#version[version segment] to the unversioned component version's page and asset URLs, even if the xref:playbook:urls-latest-version-segment.adoc[latest_version_segment key] or xref:playbook:urls-latest-prerelease-version-segment.adoc[latest_prerelease_version_segment key] is set in the playbook

[TIP]
.UI and extension developers
====
When a component version is defined as unversioned:

* the reserved version value, `~` or `null`, is coerced into and stored as an empty string internally
* a version segment isn't added to `pub.url` or `out.path`
====

== Reference an unversioned resource

Because an unversioned component version is often the only version or always the latest component version in a component, Antora automatically routes any incoming references that originate from other components that don't specify a version coordinate to it.
However, in rare cases, such as when referencing an unversioned prerelease from another component version, you can use the reserved keyword `+_+` (an underscore) as the version coordinate in the xref:page:page-id.adoc#id-coordinates[page ID] or xref:page:resource-id.adoc#id-coordinates[resource ID] (e.g., `+xref:_@component:module:file-name.adoc[]+`) to reference an unversioned component version.
