= Repositories and Content Source Roots

Antora collects content source files from branches, tags, and directories in git repositories.
These source files are only retrieved and processed correctly if Antora can locate them at a specified content source root.
//and then categorize them using a valid component version descriptor file and standard directory set.

== git repositories as content sources

The source files containing a site's content are stored in git repositories.
These repositories can be remote, local, or a mix of both.
A [.term]*content source* is the route--a git reference and start path--that leads to a unique <<content-source-root,content source root>>.
Content sources are specified in an Antora playbook file.
But before configuring your site's playbook, you need to set up the required directories and sorted your content source files into them at each content source root.

[#content-source-root]
== What is a content source root?

A [.term]*content source root* is a unique location from where Antora begins collecting content source files.
Think of the content source root as the starting line for a race.
From a content source root, Antora expects to find an [.path]_antora.yml_ file and a collection of source files that are organized into a xref:standard-directories.adoc[standard set of directories].
A repository can host a multitude of content source roots, even within a single branch in certain scenarios.

////
A content source root is specified by a git reference and start path that's configured in a playbook file.
The git reference is the URL or file system location of a repository and specified branch or tag.
The start path is where Antora should find a component version descriptor file named [.path]_antora.yml_ and the required directory structure.
Because a git reference (repository + branch/tag) can lead to numerous unique locations when a start path is specified, a single repository branch or tag can contain more than one content source.
////
