= Content Source Versioning Methods
:page-aliases: component-versions.adoc

== Component versions and branches

Although there isn't necessarily a relationship between version control repository branches or tags, as specified in the playbook, and component versions, relating these results in a simple, convenient, flexible, and easy to understand organization.

In this scheme, versions of a documentation component are stored in branches in a version control repository such as git.
The name of the branch itself doesn't matter.
It's the xref:component-name-and-version.adoc#version-key[version key] in the xref:component-version-descriptor.adoc[component version descriptor] that determines the version.

== Version content using branches

As with software, in this scheme we use branches to store different versions of the documentation.
Branches are ideally suited for managing multiple versions of the same content.

If we didn't use branches to specify versions, but instead used, for example, folders with trailing version numbers in a single branch, then we'd have to explicitly duplicate all the files in a documentation component for each version.
And we'd have no easy way to compare, manage, and merge different instances of a document.

Branches handle this for us.
Creating a new branch is extremely cheap.
You simply create a new branch from an existing reference in the repository, and the repository only stores what's changed since that branch point.

== Version content using tags

== Version content using directories


== Learn more
// The list items IDs exist because they're the previous section IDs for sections that were originally in the aliased page, but have now become their own pages.

* xref:component-name-and-version.adoc[Define a component name and version with antora.yml]
* [[version-sorting]]xref:how-component-versions-are-sorted.adoc[How are component versions sorted?]
* [[versionless-urls]]xref:component-with-no-version.adoc[Define a component version with no version]


////
This section is going to become a new page

== Setting the version for a branch

To assign a version to a component version stored in a particular branch, you set the xref:component-name-and-version.adoc#version-key[version key in the component version descriptor]:

[source,yaml]
----
name: versioned-component
version: '2.1'
title: Versioned Component
----

This component version descriptor communicates that the files taken from this branch contribute to the `2.1` version of the component named `versioned-component`.
The name of the branch where the component version's source files are stored could be _v2.1_ or _v2.1-beta_.
It doesn't matter.

The component version descriptor is the only file you have to update when creating a new branch.
All the page references for that component version should be relative to the version, so you shouldn't need to update any links.
The next time you run Antora on the repository, you'll see a new version in the component explorer drawer.

You may need to add the xref:playbook:configure-content-sources.adoc#branches[branch to your playbook file].
Keep in mind that content sources are filtered by branch name, not by the version they contain.
That's because xref::component-structure.adoc#distributed[a single component version's source files can be located in multiple branches, or even multiple repositories].
////
