= Images Directory and Files

[#images-dir]
== Images family directory

A module directory can contain an xref:family-directories.adoc[optional family directory] named [.path]_images_.

[listing]
----
📂 modules
  📂 ROOT
    📂 images <.>
      📄 a-source-file.gif <.>
      📄 a-source-file.jpg
    📂 pages
      📄 a-source-file.adoc
    📄 nav.adoc
----
<.> An [.path]_images_ family directory in a [.path]_ROOT_ module directory
<.> An image source file

Antora applies preset behavior to the source files stored in an [.path]_images_ directory when it generates a site.

[#images]
== Image files

xref:page:images.adoc[Images] are resources, such as photographs, diagrams, and screenshots.
The source files for images are stored in an [.path]_images_ family directory.
Antora supports the PNG, JPG, SVG, and GIF (static and animated) image file formats.

Regardless of the component version the image belongs to, the image can be embedded into a page or partial using the image's resource ID and an AsciiDoc xref:page:block-images.adoc[block image macro] or xref:page:inline-images.adoc[inline image macro].

Antora automatically publishes each image file, except when the image file is marked as xref:standard-directories.adoc#hidden-files[hidden or it's missing a file extension].
Antora uses the xref:how-antora-builds-urls.adoc#family[family segment] and xref:how-antora-builds-urls.adoc#relative-path[relative path segment of the image file] when building the URL for an image.

include::partial$assets-directory.adoc[]
