= Install and Run Antora Quickstart
:listing-caption!:
:url-demo: https://gitlab.com/antora/demo

This quickstart walks you through the initial steps required to install Antora and generate your first documentation site.

On this page, you’ll learn:

* [x] How to install Node.js.
* [x] How to install Antora.
* [x] How to create your first Antora playbook.
* [x] How to run Antora to generate a site based on the playbook.

You can skip the installation steps by using the xref:antora-container.adoc[Docker image] provided by the Antora project.
Instead of having to worry about installing Node.js and Antora, all you need is Docker or Podman to run Antora in a container.

[#install-nodejs]
== Install Node.js

Antora requires an active long term support (LTS) release of Node.js.
To see if you have Node.js installed, and which version, open a terminal and type:

 $ node -v

This command should return an {url-node-releases}[active Node.js LTS version number], for example:

[subs=+attributes]
 $ node --version
 v{version-node}

If you have an active Node.js LTS version on your machine, you're ready to <<install-antora,install Antora>>.

If *no version number is displayed in your terminal*, you need to install Node.js.
We recommend using nvm to install Node.js, though you are free to take a different path.
Follow one of these guides to learn how to install nvm and Node.js on your platform.

* xref:install:linux-requirements.adoc#install-nvm[Install nvm and Node.js on Linux]
* xref:install:macos-requirements.adoc#install-nvm[Install nvm and Node.js on macOS]
* xref:install:windows-requirements.adoc[Install nvm and Node.js on Windows]

If *you have Node.js installed, but it isn't an active LTS version*, you need to upgrade Node.js.
To upgrade to the latest Node.js LTS version and set it as your default version, type the following commands in your terminal:

.Linux and macOS
[subs=+attributes]
 $ nvm install --lts
 $ nvm alias default {version-node-major}

.Windows
[subs=+attributes]
 $ nvm install {version-node}
 $ nvm alias default {version-node}

Once you've installed Node.js, it's time to install Antora.

[#install-antora]
== Install Antora

To generate documentation sites with Antora, you need the Antora command line interface (CLI) and the Antora site generator.
To install Antora, begin by making a new directory for your site named [.path]_docs-site_ and switch to it.

 $ mkdir docs-site && cd docs-site

Next, let's initialize a [.path]_package.json_ file and install the required packages within the playbook project so you can run the `antora` command using `npx`.

[subs=+attributes]
 $ node -e "fs.writeFileSync('package.json', '{}')"
ifdef::page-component-version-is-latest[]
 $ npm i -D -E antora
endif::[]
ifndef::page-component-version-is-latest[]
 $ npm i -D -E antora@{page-component-version}
endif::[]

NOTE: Refer to xref:security-bulletins.adoc[] to remediate any security vulnerabilities that are reported.

Verify the `antora` command is available by running:

 $ npx antora -v

If the installation is successful, the command will report the version of the Antora CLI and site generator packages you specified.

[subs=+attributes]
 $ npx antora -v
 @antora/cli: {release-version}
 @antora/site-generator: {release-version}

These versions can also be found in [.path]_package.json_ (pulled in transitively by the antora package), which you can use to upgrade Antora.

You have the option of installing Antora globally so that the `antora` command is available on your PATH.
To do so, pass the `-g` option to `npm i`.

[subs=+attributes]
ifdef::page-component-version-is-latest[]
 $ npm i -g antora
endif::[]
ifndef::page-component-version-is-latest[]
 $ npm i -g antora@{page-component-version}
endif::[]

You can verify that the `antora` command is available on your path by running:

 $ antora -v

We strongly recommend that you install Antora within the playbook project.
This strategy makes it easier to manage the version of Antora.
It also ensures that the version of Antora matches the version for which the playbook was made.

Now you're ready to create your first playbook.

TIP: See xref:install:install-antora.adoc[Install Antora] for more detailed information and additional installation methods.

== Create a playbook

To produce a documentation site, Antora needs a playbook.
Using your preferred text editor or IDE, create a new file and populate it with the configuration information <<demo-playbook,listed below>>.
Save this file as [.path]_antora-playbook.yml_ in the [.path]_docs-site_ directory you made in the previous step.
This playbook file will create a site using the {url-demo}[Antora demo repositories].

.antora-playbook.yml
[#demo-playbook,yaml]
----
site:
  title: Antora Docs
  start_page: component-b::index.adoc # <.>
content:
  sources: # <.>
  - url: https://gitlab.com/antora/demo/demo-component-a.git
    branches: HEAD
  - url: https://gitlab.com/antora/demo/demo-component-b.git
    branches: [v2.0, v1.0]
    start_path: docs
ui: # <.>
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
----
<.> A page from a component version to be used as the home page for your site.
<.> The `sources` category contains the list of git repository locations, branch name patterns, and other repository properties that Antora uses when aggregating the site content.
<.> The `ui` category contains keys that specify the location of the UI bundle and how it should be processed.

TIP: See the xref:playbook:index.adoc[Antora playbook] for more detailed information about the playbook file.

== Run Antora

To generate the site, point the `antora` command at your playbook file.
In the terminal, make sure you're in [.path]_docs-site_ directory, then type:

 $ npx antora --fetch antora-playbook.yml

Antora will clone the content and UI repositories and generate your documentation site to the default output directory.

IMPORTANT: By default, Antora does not sync the repository once it clones it.
Instead, it tries to work offline by using the repository in the cache it previously cloned.
This default can create some confusion when getting started.
Therefore, we recommend including the xref:playbook:runtime-fetch.adoc#fetch-option[`--fetch` option] in the command until you're more familiar with Antora.
You can also set the xref:playbook:runtime-fetch.adoc#fetch-key[fetch key] in your playbook to enable this setting permanently.

Navigate to the [.path]_docs-site/build/site_ directory and open the [.path]_index.html_ file in your browser to see the result.
Congratulations!
You've successfully built your first site with Antora.

TIP: For more detailed information about running Antora and troubleshooting help, see xref:run-antora.adoc[Run Antora to generate your site].

== Learn more

* Learn how to xref:organize-content-files.adoc[organize your content files] for Antora.
