= Recommendations for Module Directory Names
:xrefstyle: short
:listing-caption: Example

When you're creating module directories, you need to consider the team using them and your site's URLs.

== Selecting module directory names

Antora calculates the xref:named-module-directory.adoc#named-module[name of a module] from the name of a xref:module-directories.adoc#module-dir[module directory].
A module name is used in page cross references, image macros, and include directives.
It's also used in the xref:module-url-segment.adoc#named-module-urls[URLs of the pages assigned to that module].

When choosing a module directory name, keep the following requirements and recommendations in mind:

* Named module directories *can't contain blank spaces or forward slashes (`/`)*.
These characters aren't permitted in AsciiDoc cross references, image macros, or include directives.
* If possible, *don't use uppercase letters, underscores (`_`), and other characters that aren't recommended in URLs*.
Such characters can limit web server portability, downgrade site search results, and cause visitor accessibility problems.
* If your team often references pages, examples, images, or partials across modules, they'll have to type a module's name in page and resource IDs, so *don't make the directory name hard to remember or extremely long*.

<<fig-named>> shows a standard directory structure that contains three named module directories.

[#fig-named]
.Three named module directories
----
📒 repository
  📂 docs
  📄 antora.yml
  📂 modules
    📂 gear <1>
      📂 images
        📄 a-source-file.jpg
    📂 la-garita <2>
      📂 pages
        📄 a-source-file.adoc
    📂 ROOT <3>
      📂 pages
        📄 a-source-file.adoc
      📄 nav.adoc
    📂 sdk <4>
      📂 examples
        📄 a-source-file.js
      📂 pages
        📄 a-source-file.adoc
      📄 nav.adoc
----
<1> Module directory named [.path]_gear_
<2> Module directory named [.path]_la-garita_
<3> [.path]_ROOT_ module directory
<4> Module directory named [.path]_sdk_

Antora would calculate the following module names from the named module directories in <<fig-named>>: `gear`, `la-garita`, and `sdk`.
