= Module Directories and Modules
:page-aliases: modules.adoc

[#modules-dir]
== What's the modules directory?

The [.path]_modules_ directory is required wherever a component version descriptor file ([.path]_antora.yml_) is located.

----
📒 repository
  📂 docs <1>
    📄 antora.yml <2>
    📂 modules <3>
    📂 a-directory <4>
----
<1> Content source root
<2> Required component version descriptor file
<3> Required [.path]_modules_ directory
<4> Antora won't process the files in this directory because it's located outside the [.path]_modules_ directory

Except for [.path]_antora.yml_, the standard directories and their files must reside in a valid hierarchy in the [.path]_modules_ directory.
A [.path]_modules_ directory can contain as many <<module-dir,module directories>> as you require.

The [.path]_modules_ directory may seem unnecessary, but it keeps documentation source files separate from application code, tests, and other materials if a xref:content-source-repositories.adoc#content-source-root[content source root] is located in a repository that stores non-documentation projects.

[#module-dir]
== What's a module directory?

Module directories must be stored in a <<modules-dir,_modules_ directory>>.
A [.term]*module directory* stores the source files for pages, reusable text and example snippets, images, and other content, in one or more xref:family-directories.adoc[family directories].
The source files stored in a module directory become part of a <<module,module>> in a component version.

----
📒 repository
  📂 docs <1>
    📄 antora.yml
    📂 modules
      📂 a-named-module <2>
        📂 pages <3>
          📄 a-source-file.adoc <4>
        📄 nav.adoc <5>
----
<1> Content source root
<2> A named module directory
<3> _pages_ family directory
<4> A source file for a page
<5> A navigation file

At a minimum, a module directory must contain at least one xref:family-directories.adoc[family directory] with at least one source file.
A module directory can also contain an optional navigation file.

There are two types of module directories: xref:named-module-directory.adoc[named module directories] and xref:root-module-directory.adoc[ROOT module directories].
At runtime, Antora collects the source files stored in the ROOT and named module directories and assigns them to modules.
The <<module,module>> corresponds to the name of the module directory.
For this reason, it's important to carefully consider what files you store in a [.path]_ROOT_ module directory and xref:module-directory-names.adoc[what you name your named module directories].

[#module]
== What's a module?

Antora classifies, assembles, and publishes the content of a xref:component-version.adoc[component version] into one or more modules.
A [.term]*module* is a collection of content that's typically related by concept, stage, feature, or other project-specific criteria.
Antora determines the module a source file belongs to according to its module name.

A [.term]*module name* is a unique identifier Antora calculates based on the name of the module directory from where it retrieved the content's source files.

////
[#where-module-name-is-used]
== Where is the module name used?

When inserting or linking to content that belongs to another module, you'll specify the target module's name in the page IDs of cross references and the resource IDs for images, examples, and partials.

In addition to internal processes, Antora uses the module name, except for `ROOT`, as a xref:module-url-segment.adoc[segment in page URLs].
////

////
All of the content that is assigned to a specific module is often stored in a single <<module-dir,module directory>>.
However, a module can also be assembled from files stored at multiple content source root locations as long as the assigned component name and version are the same and the name of each module directory the content is retrieved from is the same.

Antora applies additional preset behavior to the files stored in a [.path]_ROOT_ module directory.

As for named module directories, carefully consider the names you give to these directories because they're used during site configuration and generation.
Antora extracts the name of a module directory and assigns this name as the module coordinate to the source files stored in that directory.

[#nav-files]
== Navigation files

A module can contain none, one, or numerous navigation files.
A xref:navigation:filenames-and-locations.adoc[navigation file] is an AsciiDoc file (e.g., [.path]_nav.adoc_) that is stored in the directory of the module, but not in any of the module's family subdirectories.
In order to be displayed in the xref:navigation:index.adoc[component version's page menu], a navigation file must be xref:component-navigation.adoc[declared in the component version descriptor].
////
