= Named Module Directory

== What's a named module directory?

Named module directories are xref:module-directories.adoc#module-dir[optional module directories] that are located in a xref:module-directories.adoc#modules-dir[_modules_ directory].
You can create as many named module directories as you need.

.Named module directories
[listing#ex-named]
----
📒 repository
  📂 docs <.>
    📄 antora.yml <.>
    📂 modules <.>
      📂 a-named-module <.>
        📂 pages <.>
          📄 a-source-file.adoc <.>
        📄 nav.adoc <.>
      📂 get-started <.>
        📂 pages
          📄 a-source-file.adoc
----
<.> Content source root
<.> Required [.path]_antora.yml_ file
<.> Required [.path]_modules_ directory
<.> A named module directory
<.> [.path]_pages_ family directory
<.> A source file for a page
<.> A navigation file
<.> Another module directory, named [.path]_get-started_

Antora uses a module's directory name to create a <<named-module,module's name>>.
For this reason, it's important to carefully consider xref:module-directory-names.adoc[what you name your named module directories].
At a minimum, a named module directory must contain at least one xref:family-directories.adoc[family directory] with at least one source file.
A named module directory can also contain an optional navigation file.

[#named-module]
== What's a named module?

Source files in each named module directory become part of a named module in a xref:component-version.adoc[component version].
The name of a module corresponds to the name of a module directory.
For instance, source files stored in the [.path]_get-started_ module directory shown in <<ex-named>> will be assigned to the module `get-started`.

[#where-name-is-used]
== Where's a module's name used?

When you target content that belongs to a named module from another module or component version, you'll specify the module's name in the xref:page:resource-id.adoc[resource IDs] for pages, attachments, images, examples, and partials.

The module's name is also used as a xref:module-url-segment.adoc#named-module-urls[segment in the publishable resource URLs].
