= Pages Directory and Files

[#pages-dir]
== Pages family directory

A module directory can contain an xref:family-directories.adoc[optional family directory] named [.path]_pages_.
Only AsciiDoc source files with the file extension (_.adoc_) should be stored in the [.path]_pages_ directory because Antora applies preset behavior to these files when it runs.

[listing]
----
📂 modules
  📂 a-named-module <.>
    📂 pages <.>
      📄 a-source-file.adoc <.>
  📂 ROOT
    📂 pages
      📄 a-source-file.adoc
    📄 nav.adoc
----
<.> A named module directory
<.> [.path]_pages_ family directory
<.> AsciiDoc source file with valid _.adoc_ file extension

A [.path]_pages_ family directory must contain at least one AsciiDoc source file.

[#pages]
== Page files

Pages are source files stored in a [.path]_pages_ directory.
xref:page:index.adoc[Pages] are marked up using the AsciiDoc syntax and saved with the _.adoc_ file extension.
Regardless of the component version the page is assigned to, a xref:page:xref.adoc[page can be cross referenced] by any page, resource, or navigation file.

Antora automatically converts each page to HTML and publishes it as an individual page in a site.
(Except when the page file is marked as xref:standard-directories.adoc#hidden-files[hidden or it's missing a file extension].)
Antora uses the xref:how-antora-builds-urls.adoc#relative-path[relative path segment of the page file] when building the URL of a page.
