= Partials Directory and Partial Files

[#partials-dir]
== Partials family directory

A module directory can contain an optional xref:family-directories.adoc[family directory] named [.path]_partials_.

----
📂 modules
  📂 a-named-module
    📂 partials <1>
      📄 a-source-file.adoc <2>
  📂 ROOT
    📂 pages
      📄 a-source-file.adoc
    📂 partials <3>
      📄 a-source-file.csv <4>
    📄 nav.adoc
----
<1> A [.path]_partials_ family directory in a named module directory
<2> A partial AsciiDoc source file
<3> A [.path]_partials_ family directory in a [.path]_ROOT_ module directory
<4> A partial source file

Antora applies preset behavior to the source files stored in the [.path]_partials_ directory when it generates a site.

[#partials]
== Partials

[.term]*Partials* are usually AsciiDoc source files (_.adoc_) that contain content snippets, such as common descriptions, terminology, or reference tables, that you plan to insert in multiple pages.
They may also be reusable UML, STEM, or CSV/TSV content.
The source files for partials are stored in a [.path]_partials_ directory.

If a partial isn't referenced in an AsciiDoc include directive, its content won't be published to a site (unlike xref:pages-directory.adoc#pages[pages], which are always automatically published).
Partials and tagged regions in a partial can be inserted into any page, regardless of the module or component version that page belongs to, using the xref:asciidoc:include-partial.adoc[include directive and the partial's resource ID].

When referencing a partial, the `partial` family name must be included in its resource ID.
The family name, `partial`, is required because the include directive is also used to reference xref:examples-directory.adoc[example source files].
