= Partials Directory and Files

[#partials-dir]
== Partials family directory

A module directory can contain an xref:family-directories.adoc[optional family directory] named [.path]_partials_.

[listing]
----
📂 modules
  📂 ROOT
    📂 pages
      📄 a-source-file.adoc
    📂 partials <.>
      📄 a-source-file.adoc <.>
    📄 nav.adoc
----
<.> A [.path]_partials_ family directory in a [.path]_ROOT_ module directory
<.> A partial source file

Antora applies preset behavior to the source files stored in the [.path]_partials_ directory when it generates a site.

[#partials]
== Partial files

Partial files, or partials for short, are resources that contain content snippets, such as common descriptions, terminology, or reference tables, that can be reused in one or more pages.
Partials are stored in a [.path]_partials_ directory.

Antora doesn't automatically publish partial files.
A xref:page:include-a-partial.adoc[partial must be referenced by an include directive] from a page, or resource that's eventually included in a page, for the partial's content to be published.
