= ROOT Module Directory

[#root-dir]
== What's a ROOT module directory?

The [.path]_ROOT_ directory is an xref:module-directories.adoc#module-dir[optional module directory].
A [.path]_ROOT_ module directory is located in a xref:module-directories.adoc#modules-dir[_modules_ directory], and its name must be written in all uppercase letters.
A [.path]_ROOT_ directory stores content source files in one or more of the xref:family-directories.adoc[family directories].

----
📒 repository
  📂 docs <1>
  📄 antora.yml <2>
  📂 modules <3>
    📂 ROOT <4>
      📂 pages <5>
        📄 a-source-file.adoc <6>
      📄 nav.adoc <7>
----
<1> Content source root
<2> Required [.path]_antora.yml_ file
<3> Required [.path]_modules_ directory
<4> [.path]_ROOT_ module directory
<5> [.path]_pages_ family directory
<6> A source file for a page
<7> A navigation file

At a minimum, a [.path]_ROOT_ module directory must contain at least one xref:family-directories.adoc[family directory] with at least one source file.
It can also contain an optional navigation file.

The source files stored in a [.path]_ROOT_ directory become part of a <<root-module,ROOT module>> in a component version.
It's recommended that you create a [.path]_ROOT_ module directory because Antora applies special preset behavior to the pages in a <<root-module,ROOT module>>.

Small documentation projects may never need more than a [.path]_ROOT_ module directory.
However, as your project grows, you can easily add more module directories and gradually reorganize your source files.
While the extra structure seems like overkill now, in the long run, you'll be glad you gave your content the space to grow.

[#root-module]
== What's a ROOT module?

Source files that are stored in a [.path]_ROOT_ directory become part of a module named `ROOT` in a xref:component-version.adoc[component version].
A ROOT module's pages become the top-level pages of a component version.

[#where-root-name-is-used]
== Where is the ROOT module name used?

When you target content that belongs to a ROOT module from another module or component version, you'll specify the module name `ROOT` in the page IDs of cross references and the resource IDs for images, examples, and partials.
`ROOT` is always written in uppercase letters when it's specified.

Since Antora considers the pages in a ROOT module to be top-level component version pages, the module name `ROOT` isn't displayed in the xref:module-url-segment.adoc#root-module-urls[module segment of its page URLs].
