= When to Use Each Type of Version
//Manage Version Types
//When to Use Each Type of Version
//Comparison on Version Keys
//Actual, Prerelease, Display and Symbolic Version Comparison

== Version types

[#actual]
=== Actual version

The [.term]*actual version* is an identifier, that when combined with a component name, creates a unique identity for a collection of content and source files that are directly related to one another.
This collection of source files is a xref:component-version.adoc[component version].
A component version always has an actual version.
Even a component version that isn't versioned uses the tilde (`~`) or `null` identifier as its actual version.

A component version's actual version is assigned to the xref:ROOT:component-name-and-version.adoc#version-key[version key] in its component version descriptor (_antora.yml_).
Alternatively, the actual version is extracted by Antora from a git refname based on the pattern assigned to the `version` key in [.path]_antora.yml_ or on a content source in a playbook.

Content writers use the actual version to reference pages and assets in other component versions.
Antora uses the actual version:

* to sort component versions
* to identify the latest version of a component
* to apply routing rules
* for display purposes in the reference UI
* as the version segment in the published URLs

The version types described in the following sections override one of the default behaviors in a generated site where Antora would otherwise use the actual version.

=== Prerelease version

A version of a project or product that is made available before its final release is often called a [.term]*prerelease version*.
Organizations use semantic versioning identifiers, such as `alpha` or `beta`, or special names, such as `edge`, to communicate that a version is a prerelease to end users.
To compliment a prerelease version of a project, a component version can be designated as a prerelease using the `prerelease` key.

A component version is designated as a prerelease when the `prerelease` key is assigned an xref:component-prerelease.adoc#identifier[identifier] or the value xref:component-prerelease.adoc#true[true] in its [.path]_antora.yml_ file.
Using the `prerelease` key has the following benefits:

* While the component version is a prerelease, Antora won't route incoming page and resource ID references from other component versions to the prerelease version if the version coordinate wasn't specified or can't be determined.
Instead, Antora routes such references to the latest stable version of the component.
* The `prerelease` key allows the actual version (`version`) of the component version to represent the stable version from the inception of the component version.
Therefore, the published URLs of the component version and inbound references from other component versions aren't affected when the component version graduates from a prerelease to a stable release.
* Unless the `display_version` key is assigned a value or `prerelease` is assigned `true`, the prerelease identifier is appended to the actual version and displayed in the reference UI menus, showing end users that the component version is a prerelease.

[#display]
=== Display version

An actual version can't contain spaces, uppercase letters, or certain characters that cause processing or portability errors.
However, the actual version, when displayed in the reference UI menus, may not provide the appropriate experience if end users are expecting the version to be displayed with spaces, uppercase letters, or other symbols.
In these circumstances, a display version should be assigned to a component version.

A [.term]*display version* is an identifier that is only used for presentation purposes in the reference UI menus.
Unlike the actual version, the display version can contain spaces, uppercase letters, and other symbols or characters.
The display version is specified using the `display_version` key in a component version's [.path]_antora.yml_ file.
The display version is used by the reference UI where the version is displayed, including the xref:navigation:index.adoc#component-dropdown[component version selector] and xref:navigation:index.adoc#page-dropdown[page version selector].
The display version is never used in page or resource IDs, for component version routing and sorting, or in the version segment of URLs.

[#symbolic]
=== Symbolic version and symbolic prerelease version

A [.term]*symbolic version* or [.term]*symbolic prerelease version* is a value that replaces the actual version in the version segment of a URL.
The symbolic version or prerelease version are only applied to the URLs of the xref:ROOT:how-component-versions-are-sorted.adoc[latest component versions or latest prereleases], respectively.
The symbolic version value is assigned to the `latest_version_segment` key in the playbook.
The symbolic prerelease version value is assigned to the `latest_prerelease_version_segment` key in the playbook.

== Summary of version types

[%header,cols="h,1,2,2,1"]
|===
|Type
|Page and resource IDs
|Sorting order and routing
|Menus in reference UI
|Version segment in URLs

|Actual
|Yes
|Yes
|Yes

_Exceptions:_

If `prerelease` is assigned an identifier, the actual version is appended with the identifier when displayed.

If a value is assigned to `display_version`, the display version is shown instead of the actual version.
|Yes

_Exception:_

If a value is assigned to `latest_version_segment`, the actual version is replaced by the symbolic version.
This behavior only applies to the URLs of the latest component versions that aren't marked as prereleases.

|Prerelease
|No
|Yes
|Yes

_Exceptions:_

If `prerelease` is assigned `true`, only the actual version is displayed.

If a value is assigned to `display_version`, the display version is shown instead of the actual version or prerelease identifier.

|No

_Exception:_

If a value is assigned to `latest_prerelease_version_segment`, the actual version is replaced by the symbolic prerelease version.
This behavior only applies to the URLs of the latest prerelease version of a component.

|Display
|No
|No
|Yes
|No

|Symbolic
|No
|No
|No
|Only applies to the latest versions of components.

|Symbolic prerelease
|No
|No
|No
|Only applies to the latest prerelease versions of components.
|===
