= What's New in Antora {page-component-version}
:description: The new features, changes, and bug fixes included in Antora {page-component-version} and its patch releases.
:doctype: book
:route: New
//:page-toclevels: 0
:leveloffset: 1
:url-releases-asciidoctor: https://github.com/asciidoctor/asciidoctor/releases
:url-releases-asciidoctorjs: https://github.com/asciidoctor/asciidoctor.js/releases
:url-gitlab: https://gitlab.com
:url-issues: {url-repo}/issues
:url-milestone-3-1-0: {url-issues}?scope=all&state=closed&label_name%5B%5D=%5BVersion%5D%203.1.0
:url-mr: {url-repo}/merge_requests

IMPORTANT: *Antora 2.3 is EOL*.
If you're still using Antora 2, review the checklist on xref:install:upgrade-antora.adoc[] to learn about what changes you should make to your source content and Antora configuration prior to upgrading to Antora {page-component-version}.

= Antora {page-component-version}.0

_**Release date:** Unreleased | *Issue label:* {url-milestone-3-1-0}[3.1.0^]_

//The Antora {page-component-version}.0 release introduces an event-based extension facility and structured logging, delivers the latest Asciidoctor capabilities, and adds new ways to manage versions.
These are just a few of the new capabilities and updates packed into Antora {page-component-version}.

== Resolved issues

=== Added

Issue {url-issues}/814[#814^]:: Add `removeFile` method to the content catalog and UI catalog.
Issue {url-issues}/978[#978^]:: Add `origins` property containing unique origin objects to each entry in the content aggregate.
Issue {url-issues}/981[#981^]:: Resolve attribute references in AsciiDoc attributes defined in the playbook ([.path]_antora-playbook.yml_) and component version descriptors ([.path]_antora.yml_).

=== Changed

Issue {url-issues}/979[#979^]:: Set Node.js 16.0.0 as minimum supported Node.js version.
Upgrade dependencies that require Node.js > 12 and remove workarounds.
Issue {url-issues}/982[#982^]:: Move logic to collate AsciiDoc attributes to a helper function.
Use helper function to collate AsciiDoc attributes from playbook and component version.

=== Removed

Node.js 12 and 14 support:: Antora no longer supports Node.js 12 and 14.

// === Fixed
//=== Maintenance


[#thanks-3-1-0]
== Thank you!

Most important of all, a huge *thank you!* to all the folks who helped make Antora even better.
The {url-chat}[Antora community] has provided invaluable feedback and testing help during the development of Antora {page-component-version}.

We also want to call out the following people for making contributions to this release:

Gautier de Saint Martin Lacaze ({url-gitlab}/jabby[@jabby^]):: Add `removeFile` method to `contentCatalog` and `uiCatalog` ({url-issues}/814[#814^]).

////
Alexander Schwartz ({url-gitlab}/ahus1[@ahus1^])::
Andreas Deininger ({url-gitlab}/deining[@deining^])::
Ben Walding ({url-gitlab}/bwalding[@bwalding^])::
Daniel Mulholland ({url-gitlab}/danyill[@danyill^])::
Ewan Edwards ({url-gitlab}/eedwards[@eedwards^])::
George Gastaldi ({url-gitlab}/gastaldi[@gastaldi^])::
Germo Görtz ({url-gitlab}/aisbergde[@aisbergde^])::
Guillaume Grossetie ({url-gitlab}/g.grossetie[@g.grossetie^])::
Hugues Alary ({url-gitlab}/sturtison[@sturtison^])::
Jared Morgan ({url-gitlab}/jaredmorgs[@jaredmorgs^])::
Juracy Filho ({url-gitlab}/juracy[@juracy^])::
Marcel Stör ({url-gitlab}/marcelstoer[@marcelstoer^])::
Paul Wright ({url-gitlab}/finp[@finp^])::
Raphael Das Gupta ({url-gitlab}/das-g[@das-g^])::
Sturt Ison ({url-gitlab}/sturtison[@sturtison^])::
Vladimir Markiev ({url-gitlab}/Grolribasi[@Grolribasi^])::

[#checklist]
== Upgrade checklist

include::install:partial$upgrade-checklist.adoc[tag=new]

== Deprecation summary

The following deprecations are final in Antora {page-component-version}.0.

* The default branches pattern of `[master, v*]` is deprecated; the default branches pattern is now `HEAD, v{0..9}*`.
* Referencing attachments with the link macro (`+link:[]+`) and the `attachmentsdir` attribute are deprecated; use the xref:page:attachments.adoc[AsciiDoc xref macro and the resource ID of the attachment] to link to an attachment.
* Using parent references in the target of the AsciiDoc include directive; use the resource ID of the page, partial, or example, or in the case of relative files within the same family use the relative path token (`./`) instead.
* The `partialsdir` and `examplesdir` attributes are deprecated.
Use the resource ID of the xref:page:include-a-partial.adoc[partial] or xref:page:include-an-example.adoc[example] to reference the resource instead.
* Using the value `master` to represent an unversioned (empty) version when assigned to the `version` key in a component descriptor file is deprecated; use the tilde symbol (`~`) to represent an unversioned component version instead.
In Antora 4, the value `master`, when assigned to the `version` will be treated as a regular value.
* The fallback mechanism that automatically assigned the _.adoc_ file extension to the resource IDs of pages if it was missing in AsciiDoc xref macros and `page-aliases` values is deprecated in to make way for using non-AsciiDoc pages in AsciiDoc xref macros.
* isomorphic-git no longer includes the `cores` API.
Antora still honors the `cores` API, but the call to register the credential manager is now responsible for creating it because it runs before Antora loads.
Refer to xref:playbook:private-repository-auth.adoc#custom[Configure a custom credential manager] for the latest instructions.

The <<deprecated>> and <<removed>> sections list all of the deprecated and removed features in Antora {page-component-version}.
////
