= What's New in Antora {page-component-version}
:description: The new features, changes, and bug fixes included in Antora {page-component-version} and its patch releases.
:doctype: book
:route: New
//:page-toclevels: 0
:leveloffset: 1
:url-releases-asciidoctor: https://github.com/asciidoctor/asciidoctor/releases
:url-releases-asciidoctorjs: https://github.com/asciidoctor/asciidoctor.js/releases
:url-gitlab: https://gitlab.com
:url-issues: {url-repo}/issues
:url-milestone-3-1-0: {url-issues}?scope=all&state=closed&label_name%5B%5D=%5BVersion%5D%203.1.0
:url-mr: {url-repo}/merge_requests

= Antora {page-component-version}.0

_**Release date:** 2022.08.22 | *Issue label:* {url-milestone-3-1-0}[3.1.0^]_

The highlights of the Antora {page-component-version}.0 release include:

* raising the minimum version of Node.js to Node.js 16,
* locking down the exported require paths to clearly demarcate the public API,
* adding support for attribute references in the value of xref:playbook:asciidoc-attributes.adoc#references-in-values[site attributes defined in the playbook] and xref:component-attributes.adoc#references-in-values[component version attributes defined in component version descriptors],
* providing more context to log and error messages and formatting the information consistently,
* including more information about content roots in the model for use by extensions, and
* assigning additional xref:page:intrinsic-attributes.adoc#page-attributes[intrinsic page attributes] that relay more of a page's identity and origin.

You can find a summary of the issues resolved in this release below.

== Resolved issues

=== Added

Issue {url-issues}/221[#221^]:: Log info message if no references are found for content source.
Issue {url-issues}/354[#354^]:: Assign edit URL of current page, if set, to `page-edit-url` AsciiDoc attribute.
Define boolean `page-origin-private` AsciiDoc attribute if origin of page is private.
Issue {url-issues}/525[#525^]:: Attach parsed component version descriptor to `descriptor` property on origin object.
Issue {url-issues}/814[#814^]:: Add `removeFile` method to the content catalog and UI catalog.
Issue {url-issues}/921[#921^]:: Define `page-component-latest-version` AsciiDoc attribute with value of version string from latest component version.
Define boolean `page-component-version-is-latest` AsciiDoc attribute if page is in latest version of component.
See xref:page:intrinsic-attributes.adoc#page-attributes[intrinsic page attributes] for more information.
Issue {url-issues}/978[#978^]:: Add `origins` property containing unique origin objects to each entry in the content aggregate.
Issue {url-issues}/981[#981^]:: Resolve attribute references in AsciiDoc attributes defined in the xref:playbook:asciidoc-attributes.adoc#references-in-values[playbook] ([.path]_antora-playbook.yml_) and xref:component-attributes.adoc#references-in-values[component version descriptors] ([.path]_antora.yml_), honoring any escaped attribute references.
Issue {url-issues}/984[#984^]:: Define exports for all packages, locking down what paths can be required to the public API.
Issue {url-issues}/988[#988^]::
* Add `reftype` key with value of branch or tag to source object in structured log message.
* Add `reftype` property to origin object to explicitly identify type of git reference (branch or tag).
* Add `remote` key with value of remote tracking branch to source object in structured log message, if applicable.
* Add `remote` property to origin object to identify a remote tracking branch.
* Add `local` key with path of local repository to source object in structured log message, if applicable.

=== Changed

Issue {url-issues}/900[#900^]:: Include target in error message for broken or cyclic symbolic link in local content source or UI bundle directory.
Issue {url-issues}/979[#979^]:: Set Node.js 16.0.0 as minimum supported Node.js version.
Upgrade dependencies that require Node.js > 12 and remove workarounds.
Issue {url-issues}/982[#982^]:: Move logic to collate AsciiDoc attributes to a helper function.
Use helper function to collate AsciiDoc attributes from playbook and component version.
Issue {url-issues}/985[#985^]:: Add context to error and preserve cause if failure occurs when reading supplemental UI files.
Issue {url-issues}/986[#986^]:: Log warning message instead of throwing fatal error if file in worktree disappears or cannot be read.
Issue {url-issues}/988[#988^]:: Consistently format origin information in log and error messages.
Issue {url-issues}/993[#993^]:: Set `worktree` property on origin to false when branch or tag is local but not taken from worktree.
Use isolated Handlebars environment instead of the default (global) environment.

=== Fixed

* Don't append `undefined` after path of file in stack in pretty log format if line is missing.
* Make warning message about missing page layout consistent with other log messages.

=== Removed

Node.js 12 and 14 support:: Antora no longer supports Node.js < 16 (specifically dropping support for Node.js 12 and 14) since those Node.js release lines are now EOL.
This change is consistent with Antora's Node.js support policy.

== Antora 2 is EOL

*Antora 2 is EOL*.
Review the checklist on xref:install:upgrade-antora.adoc[] to learn about what changes you should make to your source content, including xref:asciidoctor-upgrade-notes.adoc[AsciiDoc syntax and Asciidoctor updates introduced in Asciidoctor 2.2], and Antora configuration prior to upgrading to from Antora 2 to Antora {page-component-version}.

[#thanks-3-1-0]
== Thank you!

Most important of all, a huge *thank you!* to all the folks who helped make Antora even better.
The {url-chat}[Antora community] has provided invaluable feedback and testing help during the development of Antora {page-component-version}.

We also want to call out the following people for making contributions to this release:

Gautier de Saint Martin Lacaze ({url-gitlab}/jabby[@jabby^]):: Add `removeFile` method to `contentCatalog` and `uiCatalog` ({url-issues}/814[#814^]).

////
Alexander Schwartz ({url-gitlab}/ahus1[@ahus1^])::
Andreas Deininger ({url-gitlab}/deining[@deining^])::
Ben Walding ({url-gitlab}/bwalding[@bwalding^])::
Daniel Mulholland ({url-gitlab}/danyill[@danyill^])::
Ewan Edwards ({url-gitlab}/eedwards[@eedwards^])::
George Gastaldi ({url-gitlab}/gastaldi[@gastaldi^])::
Germo Görtz ({url-gitlab}/aisbergde[@aisbergde^])::
Guillaume Grossetie ({url-gitlab}/g.grossetie[@g.grossetie^])::
Hugues Alary ({url-gitlab}/sturtison[@sturtison^])::
Jared Morgan ({url-gitlab}/jaredmorgs[@jaredmorgs^])::
Juracy Filho ({url-gitlab}/juracy[@juracy^])::
Marcel Stör ({url-gitlab}/marcelstoer[@marcelstoer^])::
Paul Wright ({url-gitlab}/finp[@finp^])::
Raphael Das Gupta ({url-gitlab}/das-g[@das-g^])::
Sturt Ison ({url-gitlab}/sturtison[@sturtison^])::
Vladimir Markiev ({url-gitlab}/Grolribasi[@Grolribasi^])::
////
