= What's New in Antora {page-component-version}
:description: The new features, changes, and bug fixes included in Antora {page-component-version} and its patch releases.
:doctype: book
:route: New
//:page-toclevels: 0
:leveloffset: 1
:url-releases-asciidoctor: https://github.com/asciidoctor/asciidoctor/releases
:url-releases-asciidoctorjs: https://github.com/asciidoctor/asciidoctor.js/releases
:url-gitlab: https://gitlab.com
:url-issues: {url-repo}/issues
:url-milestone-3-2-0: {url-issues}?scope=all&state=closed&label_name%5B%5D=%5BVersion%5D%203.2.0
//:url-milestone-3-2-1: {url-issues}?scope=all&state=closed&label_name%5B%5D=%5BVersion%5D%203.2.1
:url-mr: {url-repo}/merge_requests

= Antora {page-component-display-version}

_**Release date:** TBD | *Issue label:* {url-milestone-3-2-0}[3.2.0^]_

The primary focus of Antora {page-component-version} is to provide and refine certain API methods and endpoints to support the development of Antora extensions.
This release also added syntax for the inclusion and exclusion matching of worktrees and the ability to use the `ref` placeholder in the `edit_url` key.

You can find a summary of the issues resolved in this release below.

== Resolved issues

=== Added

Issue {url-issues}/535[#535^]:: Allow linked worktree to be used as content source; automatically resolve main repository location and remap HEAD reference in branches.
Issue {url-issues}/1006[#1006^]:: Use value of `versionSegment` property on component version in place of version in output path and URL of pages.
Also, set dynamic `activeVersionSegment` property on component version to indicate which version segment is in use.
Issue {url-issues}/1008[#1008^]:: Add `addSplatAlias` method to `ContentCatalog` for adding a splat (directory) alias.
Issue {url-issues}/1013[#1013^]:: Add support for `ref` placeholder to insert full name of git ref (e.g., `refs/heads/v4.0.x`) in value of `edit_url` key on content source.
Issue {url-issues}/1016[#1016^]:: Add syntax to match current branch of specific worktrees in branches pattern (for inclusion or exclusion) (e.g., `HEAD@5.8.x`).

=== Changed

Issue {url-issues}/1009[#1009^]:: Remove invalid trailing slash from value of `site.url` when building playbook and from value of `site.url` after `playbookBuilt` event (i.e., when it's provided by an extension).
Issue {url-issues}/1012[#1012^]:: Always assign the value `auth-required` to `origin.private` if the server requests credentials, even when the credentials are embedded in content source URL.
Content classifier:: Shorten `urlSegment` fragment in internal property names on ContentCatalog to `segment` (e.g., `latestVersionUrlSegment` -> `latestVersionSegment`).
Release process:: Automatically populate additional version and release attributes during release.

=== Fixed

Issue {url-issues}/1007[#1007^]:: Set `src.version` to original version segment and `src.rel.version` to actual version on splat alias file.
Issue {url-issues}/1010[#1010^]:: Fix infinite authorization loop if credentials embedded in the content source URL are empty and the repository requires authorization.
Issue {url-issues}/1018[#1018^]:: Fix crash if value of `worktrees` key on content source is `~` (`null`) and at least one branch is specified.

[#thanks-3-2-0]
== Thank you!

Most important of all, a huge *thank you!* to all the folks who helped make Antora even better.
The {url-chat}[Antora community] has provided invaluable feedback and testing help during the development of Antora {page-component-version}.

We also want to call out the following people for making contributions to this release:

Raphael ({url-gitlab}/reitzig[@reitzig^]):: Fixing an error in the edit URL documentation ({url-mr}/940[!940^]).
{url-gitlab}/stoobie[@stoobie^]:: Documenting how to uninstall Antora globally resolves ({url-issues}/1014[#1014^]).

////
Gautier de Saint Martin Lacaze ({url-gitlab}/jabby[@jabby^])
Alexander Schwartz ({url-gitlab}/ahus1[@ahus1^])::
Andreas Deininger ({url-gitlab}/deining[@deining^])::
Ben Walding ({url-gitlab}/bwalding[@bwalding^])::
Daniel Mulholland ({url-gitlab}/danyill[@danyill^])::
Ewan Edwards ({url-gitlab}/eedwards[@eedwards^])::
George Gastaldi ({url-gitlab}/gastaldi[@gastaldi^])::
Germo Görtz ({url-gitlab}/aisbergde[@aisbergde^])::
Guillaume Grossetie ({url-gitlab}/g.grossetie[@g.grossetie^])::
Hugues Alary ({url-gitlab}/sturtison[@sturtison^])::
Jared Morgan ({url-gitlab}/jaredmorgs[@jaredmorgs^])::
Juracy Filho ({url-gitlab}/juracy[@juracy^])::
Marcel Stör ({url-gitlab}/marcelstoer[@marcelstoer^])::
Paul Wright ({url-gitlab}/finp[@finp^])::
Raphael Das Gupta ({url-gitlab}/das-g[@das-g^])::
Sturt Ison ({url-gitlab}/sturtison[@sturtison^])::
Vladimir Markiev ({url-gitlab}/Grolribasi[@Grolribasi^])::
////
