= Define an Extension
:url-strict-mode: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

An Antora pipeline extension is a JavaScript function named `register` that is invoked by Antora after the playbook is built.
This function then registers event listeners that listen for zero or more xref:pipeline/event-reference.adoc[Antora pipeline events].
The event listeners hook into the execution of the Antora site generator (and other components) to do the bulk of the work of the extension.

To define an extension, start by creating a new JavaScript file (herein: _script_).
We'll name this extension [.path]_my-extension.js_.
In this file, you define a function named `register` and configure it to be exported (so that it can be called by Antora).

.my-extension.js
[source,js]
----
'use strict'

module.exports.register = () => {
}
----

You can also separate the function definition from the export statement, if you prefer that style.

.my-extension.js
[source,js]
----
'use strict'

const register = () => {
}

module.exports = { register }
----

It's good practice to start your extension file (a JavaScript module) with the statement `'use strict'`.
This statement enables strict mode across all versions of Node.js.
{url-strict-mode}[Strict mode^] activates a restricted variant of JavaScript that will catch common programming errors.
We'll exclude it from the remaining examples in this area of the documentation, but assume it is present.

TIP: This example defines the `register` function using the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions[arrow function^] syntax.
You could opt to use the more formal `function () {}` syntax if that feels more comfortable to you.

You can start by putting this script in your playbook repository.
Later on, you can publish it to a package repository such as npmjs.com so it may be shared between sites or site branches.

So far, our extension doesn't actually do anything.
Since the `register` method is a sort of listener itself, you could use it as an opportunity to perform an action immediately after the playbook is built.
Let's say hi.

.my-extension.js
[source,js]
----
module.exports.register = () => {
  console.log('Antora is running!')
}
----

While that's a fun trick, it's not really what we're after.
What we want to do is tie deeper into Antora's pipeline and do some work, perhaps even modify the content Antora is processing.
For that, we need to grab the pipeline object.
The first positional parameter of the `register` function is the pipeline object, which the pipeline function can use to retrieve it.

.my-extension.js
[source,js]
----
module.exports.register = (pipeline) => {
  pipeline.on(...)
}
----

The pipeline object is what you will use to register event listeners.
Before we get there, let's look at the second positional parameter.

The second positional parameter of the `register` function is an object of variables, which includes the playbook and extension config.
You should use object dereferencing to pick individual variables out of this object.
All event listeners can retrieve the playbook, but it could come in handy when registering listeners.
Here's how to access it from the `register` function:

.my-extension.js
[source,js]
----
module.exports.register = (pipeline, { playbook }) => {
  console.log(`Antora is building the ${playbook.site.title}.`)
}
----

That's enough poking around.
Let's get into xref:pipeline/register-extension.adoc[registering our extension], then on to xref:pipeline/add-listener.adoc[adding a listener].
