= UI Keys

The keys described below are configured under the `ui` key in a playbook.
These keys define the location of the UI bundle and control how it's processed.

.antora-playbook.yml
[source,yaml]
----
ui: # <1>
  bundle: # <2>
    url: https://example.org/docs-ui/download/latest/ui-bundle.zip # <3>
    snapshot: true # <4>
    start_path: dark # <5>
  default_layout: base # <6>
  output_dir: _/dark # <7>
----
<1> Required `ui` key
<2> Required `bundle` key
<3> Required `url` key
<4> Optional `snapshot` key
<5> Optional `start_path` key
<6> Optional `default_layout` key
<7> Optional `output_dir` key

[#ui-category]
== ui and bundle keys

The `ui` key contains keys that specify the location of the UI bundle and how it should be processed.

[#ui-bundle-key]
== url key

The `url` key under the `bundle` subcategory accepts a URL or local filesystem path to a UI bundle ZIP archive.
The filesystem path can be absolute or relative.

Learn more:

* xref:ui-bundle-url.adoc#remote-bundle[Fetch and load a remote UI bundle]
* xref:ui-bundle-url.adoc#local-bundle[Load a local UI bundle]

[#ui-snapshot-key]
== snapshot key

The `snapshot` key under the `bundle` subcategory indicates whether the URL points to a snapshot (i.e., it doesn't always point to the same artifact).
By default, Antora assumes that URL is permanent.

Learn more:

* xref:ui-bundle-url.adoc#snapshot[Mark a URL as a snapshot]

[#ui-start-path-key]
== start_path key

The `start_path` key under the `bundle` category is the path inside the bundle from which UI files should be selected.
When no value is specified, it defaults to the root of the bundle.

Learn more:

* xref:ui-bundle-url.adoc#start-path[Specify a start path for the UI files]

[#ui-default-layout-key]
== default_layout key

The `default_layout` key applies a layout template to pages that don't specify a page layout.

Learn more:

* xref:ui-default-page-layout.adoc[Specify a default page layout template in the playbook]

[#ui-output-dir-key]
== output_dir key

This key specifies the output directory path where the UI files are written in the published site.
When a UI `output_dir` isn't specified, the files are published to the [.path]_++_++_ directory relative to the root of the published site.

Learn more:

* xref:ui-output-directory.adoc[Specify an output directory for the UI files]

//supplemental_files: Supplemental file list or a directory of files to append to the UI bundle.
