= Runtime Keys

The playbook keys configured under `runtime` manage the console output, resource update behavior, and cache location.

[#runtime-key]
== runtime key

The `runtime` key specifies the cache directory location and when the cache is updated.

.antora-playbook.yml
[source,yaml]
----
runtime: # <1>
  cache_dir: ./.cache/antora # <2>
  fetch: true # <3>
----
<1> Optional `runtime` key
<2> Optional `cache_dir` key
<3> Optional `fetch` key

The `runtime` key and the key-value pairs it accepts are optional.
When `runtime` isn't set in a playbook, Antora uses the default cache directory and fetch settings.

[#runtime-reference]
== Available runtime keys

[cols="3,6,1"]
|===
|Runtime Keys |Description |Required

|`cache_dir`
|Specifies the directory where the xref:runtime-cache-directory.adoc#cache-dir[remote content sources git repositories and UI bundles] are cached.
|No

|`fetch`
|When set to `true`, the xref:runtime-fetch.adoc[fetch key] refreshes the files in the cache each time Antora runs.
|No
|===
