= UI Keys

The playbook keys configured under `ui` define the location of the UI bundle and control how it's processed.

[#ui-key]
== ui key

The `ui` key specifies the UI bundle's location, state, default page template name, and output directory.

.antora-playbook.yml
[,yaml]
----
ui: # <.>
  bundle: # <.>
    url: https://example.org/docs-ui/download/latest/ui-bundle.zip # <.>
    snapshot: true # <.>
    start_path: dark # <.>
  default_layout: base # <.>
  output_dir: _/dark # <.>
----
<.> Required `ui` key
<.> Required `bundle` key
<.> Required `url` key
<.> Optional `snapshot` key
<.> Optional `start_path` key
<.> Optional `default_layout` key
<.> Optional `output_dir` key

The `ui`, `bundle`, and `url` keys are required.
Alternatively, the `url` key can be assigned from the xref:cli:options.adoc#ui-bundle[CLI].
The other keys are optional; Antora uses their default values if they're not specified.

[#ui-reference]
== Available UI keys

[cols="3,6,1"]
|===
|UI Keys |Description |Required

|xref:ui-bundle-url.adoc#snapshot[bundle.snapshot]
|Indicates whether the URL points to a snapshot.
|No

|xref:ui-bundle-url.adoc#start-path-key[bundle.start_path]
|Accepts a path inside the UI bundle from which files should be selected.
|No

|xref:ui-bundle-url.adoc[bundle.url]
|Accepts a URL or filesystem path to a UI bundle archive.
|Yes

|xref:ui-default-layout.adoc[default_layout]
|Applies a layout template to pages that don't specify a page layout.
|No

|xref:ui-output-dir.adoc[output_dir]
|Accepts a filesystem path to the output directory where Antora writes the published site's UI files.
|No

|xref:ui-supplemental-files.adoc[supplemental_files]
|Supplemental files (aka supplemental UI) to overlay onto the UI bundle.
|No
|===
