= Git Repository URL Suffix

The `ensure_git_suffix` key tells Antora whether it should or shouldn't append the [.path]_.git_ extension to a remote content sources repository URL when it's absent.
If you're using GitHub or GitLab, you don't need to add this key in your playbook.

[#default]
== Default git repository URL suffix

By default, the `ensure_git_suffix` key is assigned the value `true`.
When `ensure_git_suffix` is `true`, Antora instructs the git client to automatically append [.path]_.git_ to any remote content sources repository URLs that are missing the suffix.

[#ensure-git-suffix-key]
== ensure_git_suffix key

The optional `ensure_git_suffix` key is set under the xref:configure-git.adoc[git key] in a playbook.
It accepts a boolean value.

false:: Antora won't append [.path]_.git_ to any xref:content-source-url.adoc[remote content sources repository URLs] that are missing the [.path]_.git_ suffix.

true:: Default value.
Antora will append [.path]_.git_ to any remote content sources repository URLs that are missing the [.path]_.git_ suffix.

If you use Team Foundation Server (TFS) or Azure DevOps, you may need to set `ensure_git_suffix` to `false` if your content sources repositories fail to clone.

.antora-playbook.yml
[source,yaml]
----
git:
  ensure_git_suffix: false
----
