= Archive Provider
:url-zip-file-format: https://en.wikipedia.org/wiki/Zip_(file_format)

In order to publish a site's files as a ZIP archive, your playbook must set the `output`, `destinations` and `provider` keys.

[#archive-provider]
== archive provider

The `provider` value `archive` publishes a site to a {url-zip-file-format}[ZIP] file.

.antora-playbook.yml
[,yaml]
----
output:
  destinations: # <.>
  - provider: archive # <.>
----
<.> The `provider` key must be configured under the `destinations` key.
<.> Under `destinations`, type a hyphen (`-`) and a blank space, then the key name `provider`, followed by a colon (`:`).
After the colon, enter a blank space, and then the built-in value name `archive`.

Unless the `path` key is specified, the default output target for the `archive` provider is [.path]_build/site.zip_.

[#path-key]
== path key

The optional `path` key designates the target path and filename of the generated ZIP archive.
If `path` isn't specified, Antora uses the default archive path value, [.path]_build/site.zip_.

The `path` key accepts a relative or absolute filesystem path.
The provider will create any interim directories as needed.
include::partial$relative-path-rules.adoc[]

[#relative-path]
=== Specify a relative path

In <<ex-rel>>, the site will be published to
the target file [.path]_blue.zip_ relative to the playbook file.

.Assign a relative path to the path key
[#ex-rel,yaml]
----
output:
  destinations:
  - provider: archive
    path: ./blue.zip
----

[#absolute-path]
=== Specify an absolute path

In <<ex-abs>>, the site will be published to [.path]_/home/user/projects/launch/blue.zip_, regardless of where the playbook is located.

.Assign an absolute path to the path key
[#ex-abs,yaml]
----
output:
  destinations:
  - provider: archive
    path: /home/user/projects/launch/blue.zip
----

// tag::multiple[]
[#publish-to-multiple-destinations]
== Publish to multiple destinations

In <<ex-multiple>>, Antora is running on a playbook file in the [.path]_tmp_ directory and publishing the site to two locations, one relative and one absolute.

.Specify multiple providers
[#ex-multiple,yaml]
----
output:
  destinations:
  - provider: fs
    path: ./releases/red
    clean: true
  - provider: archive
    path: /home/user/projects/docs-site/blue.zip
----

The site files published using the `fs` are written to the directory [.path]_tmp/releases/red_.
This directory will be removed prior to publishing since the `clean` key is assigned `true`.
The site is also published as an archive to [.path]_/home/user/projects/docs-site/blue.zip_ by the `archive` provider.
//end::multiple[]
