= Playbook Configuration Schema

On this page, you'll learn:

* [x] How to structure an Antora playbook.
* [x] The role of each playbook key.
* [x] The values each playbook key accepts.

== Playbook file structure

Here's a contrived example of a playbook file showing all the keys that can be defined.

WARNING: *Do not copy and paste this listing!*
It's only meant to serve as a reference to illustrate all the available keys and possible values in a playbook.
If you try to use it, it will *not* work.
Use the https://gitlab.com/antora/demo/docs-site/blob/master/antora-playbook.yml[Demo antora-playbook.yml] instead if you're looking for a starting point.

[source,yaml]
----
site: # <1>
  title: Docs Site # <2>
  url: https://docs.example.org # <3>
  start_page: component-b::index.adoc # <4>
  keys: # <5>
    google_analytics: XX-123456 # <6>
content: # <7>
  sources: # <8>
  - url: https://gitlab.com/antora/demo/demo-component-b.git # <9>
    branches: [v1.0, v2.0] # <10>
    tags: v3.* # <11>
    start_path: docs # <12>
asciidoc: # <13>
  attributes: # <14>
    table-caption: ~
  extensions:
  - ./lib/custom-block.js
ui: # <15>
  bundle:
    url: https://example.org/docs-ui/download/latest/ui-bundle.zip # <16>
    snapshot: true
    start_path: dark # <17>
  default_layout: base # <18>
  output_dir: _/dark # <19>
output: # <20>
  clean: true # <21>
  dir: ./public # <22>
  destinations: # <23>
  - provider: archive # <24>
runtime: # <25>
  cache_dir: ./.cache/antora # <26>
  fetch: true # <27>
----
<1> <<site-category,Site category>>
<2> <<site-title-key,Site title key>>
<3> <<site-url-key,Base URL key>>
<4> <<site-start-page-key,Start page key>>
<5> <<site-service-integration-keys,Service integration keys>>
<6> <<site-ga-key,Google analytics key>>
<7> <<content-category,Content category>>
<8> <<content-category,Content sources key>>
<9> <<sources-url-key,Content source repository URL key>>
<10> <<branches-key,Content source branches key>>
<11> <<tags-key,Content source tags key>>
<12> <<sources-start-path-key,Content source start path key>>
<13> <<asciidoc-category,AsciiDoc category>>
<14> <<asciidoc-attributes-key,AsciiDoc attributes key>>
<15> UI category
<16> UI bundle URL key
<17> Bundle start path key
<18> Default layout key
<19> UI output directory key
<20> Output category
<21> Clean output directory key
<22> Output directory key
<23> Output destinations key
<24> Output provider key
<25> Runtime category
<26> Cache directory key
<27> Fetch key

Let's explore the purpose and usage of each key and its values.

[#site-category]
== Site category

The site's global properties are defined under the `site` category in the playbook schema.
Antora applies these properties to the whole site when it is generated.

[#site-title-key]
=== title

The title of the documentation site.

Learn more:

* xref:configure-site.adoc#configure-title[Add a title to the site]

[#site-url-key]
=== url

The base URL of the published site.

Learn more:

* xref:configure-site.adoc#configure-url[Configure the site's base url]

[#site-start-page-key]
=== start_page

You can use a page from a documentation component as the index page for your site.
The start page key accepts a xref:page:page-id.adoc[page ID] as a value.

Learn more:

* xref:configure-site.adoc#configure-start-page[Configure a start page for the base url]

[#site-service-integration-keys]
=== keys

The account keys for global site services such as document search tools and Google Analytics.

[#site-ga-key]
==== google_analytics

This key associates a Google Analytics account with the site.

Learn more:

* xref:configure-site.adoc#configure-ga[Add a Google Analytics account key to the site]

[#content-category]
== Content category

The `content` category contains an array of source repository specifications.
These specifications are arranged under the `sources` subcategory.

The sources key contains the list of git repository locations, branch name patterns, and other repository properties that Antora uses when aggregating the site content.

[#sources-url-key]
=== url

The `url` key tells Antora where to find a documentation component's repository.
The key accepts any URI that git supports, including a local filesystem path.

Learn more:

* xref:configure-content-sources.adoc#local-urls[Use local content repositories]
* xref:configure-content-sources.adoc#remote-urls[Fetch remote content repositories]
* xref:private-repository-auth.adoc[Authenticate private repositories]
* xref:configure-content-sources.adoc#mixing-urls[Configure remote and local content repository URLs in the same playbook]
* xref:configure-content-sources.adoc#mix-local-remote-branches[Mix local and remote repositories and branches]

[#branches-key]
=== branches

The branches key accepts a list of branch name patterns, either as exact names or shell glob patterns (`v3.*`).
When no branches are specified for a sources `url`, Antora will use the [.term]_default branches set_, i.e., the `master` branch and every branch that begins with `v`.

Learn more:

* xref:configure-content-sources.adoc#default-branch[Use or modify the default branches set]
* xref:configure-content-sources.adoc#separate-branch-names[Separate branch names with commas or markers]
* xref:configure-content-sources.adoc#exact-branch[Specify branches by name]
* xref:configure-content-sources.adoc#glob-branch[Specify and exclude branches by glob patterns]
* xref:configure-content-sources.adoc#current-branch[Use the current local branch (HEAD)]
* xref:configure-content-sources.adoc#mix-local-remote-branches[Mix local and remote branches and repositories]

[#tags-key]
=== tags

The `tags` key (`tags`) accepts a list of tag name patterns, either as exact names or shell glob patterns.

Learn more:

* xref:configure-content-sources.adoc#default-tag[Set a default sources tag]
* xref:configure-content-sources.adoc#mix-branches-and-tags[Use tags and branches from the same content repository]

[#sources-start-path-key]
=== start_path

Antora automatically looks for the xref:ROOT:component-version-descriptor.adoc[component version descriptor] file at a the root of a repository.
When the component version isn't stored at the repository root, you need to specify the repository relative path to the component version descriptor's location using `start_path`.
The `url` identifies where the git repository is and the `start_path` identifies where [.path]_antora.yml_ is in the git repository (or local worktree).

Learn more:

* xref:configure-content-sources.adoc#add-start-path[Specify a start path for a content repository]

[#asciidoc-category]
== AsciiDoc category

The `asciidoc` category contains keys that configure the AsciiDoc processor, such as AsciiDoc document attributes and Asciidoctor extensions.

[#asciidoc-attributes-key]
=== attributes

The `attributes` key under the `asciidoc` category is a map used to define site-scoped AsciiDoc attributes.
These document attributes are applied and made available to all of a site's pages.

Learn more:

* xref:configure-asciidoc.adoc#attrs[Declare AsciiDoc site attributes]
* xref:site-attributes.adoc#assign-precedence[Allow component version and page attributes to override site attributes]

[#asciidoc-extensions-key]
=== extensions

The `extensions` key under the `asciidoc` category is an array used to specify a set of Asciidoctor extensions to register.
Each entry is either the name of an installed module or the path to a local script.
Depending on the capabilities of the extension, the extension will either be registered globally or be scoped to the AsciiDoc processor instance for a page.

Learn more:

* xref:configure-asciidoc.adoc#global-extensions[Register global Asciidoctor extensions]
* xref:configure-asciidoc.adoc#scoped-extensions[Register scoped Asciidoctor extensions]

////
== antora.yml

The file system name of the repository and branch are ignored by Antora once the content is retrieved.
Instead, metadata about the component is read from a component version descriptor file in the repository.
Inside each branch is a file named [.path]_antora.yml_ at the documentation component root.
The file defines the name and version of the component.

As an example, here's the [.path]_antora.yml_ file in the v5.0 branch of the server repository:

.antora.yml
[source,yaml]
----
name: server
title: Server
version: '5.0'
nav:
- modules/start/nav.adoc
- ...
----

This decoupling allows you to have more than one branch that provides the same version of a documentation component, which you can then toggle by configuring the branches key in the playbook.

urls:
urls html_extension_style: Controls how the URL extension for HTML pages is handled.

redirects: Generate nginx config file containing URL redirects for page aliases. Boolean

== Create a custom playbook

Instead of modifying the main playbook, you can create a custom playbook and pass it to Antora.

Start by creating a new file named [.path]_custom-antora-playbook.yml_.
Populate it as follows:

.custom-antora-playbook.yml (excerpt)
[source,yaml,subs=attributes+]
----
site:
  title: Custom Docs Site
content:
  sources:
  - url: https://github.com/my-docs/server-docs
  - url: https://gitlab.com/antora/demo/demo-component-b
    branches: v1.0
----
////
