= Site URL

[#url-key]
== url key

The `url` key for the site, defined under the xref:configure-site.adoc[site key] in the playbook, is optional, but recommended.
If this key isn't set, certain features of the site that relate to publishing are deactivated.
See <<when-should-the-site-url-be-set>> for details.

.antora-playbook.yml
[source,yaml]
----
site:
  title: Site Title
  url: https://docs.example.com
----

The `url` key defines the domain or root-relative base path of a published site.
The value of `url` can be an absolute URL (_\https://docs.example.com_, _\https://example.com/docs_) or a root-relative path (e.g., _/products_).
*Do not include a trailing forward slash* unless the value is only a bare forward slash.

The site URL appears in the generated site wherever an absolute URL or domain-relative path is required.
See xref:ROOT:how-antora-builds-urls.adoc[] to learn more.

Alternatively, the `url` key can be assigned from the xref:cli:options.adoc#site-url[CLI] or using its xref:environment-variables.adoc[environment variable].

[#absolute-site-url]
== Configure an absolute site URL

An absolute URL value must start with a URL scheme directly followed by a colon and two forward slashes (e.g., `https://`).

.antora-playbook.yml
[source,yaml]
----
site:
  title: Dev Docs for Example Site
  url: https://dev.example.com
----

Absolute site URLs can include a subpath (_\https://example.com/docs_, _\https://example.com/path/to/subfolder_).
The [.term]*subpath*, also known as a *path segment* or *pathname*, represents the location from the root of the domain where the site managed by Antora is located.
That is, if your site is published to a subfolder of your domain then the absolute site URL should include this path.
See <<subpath>> for more information about publishing your site to a domain subfolder.

.antora-playbook.yml
[source,yaml]
----
site:
  title: Docs for Example Site
  url: https://example.com/docs
----

When an absolute site URL has a subpath, Antora extracts the subpath and assigns it to the xref:ROOT:how-antora-builds-urls.adoc#pathname[site pathname] (_docs_, _path/to/subfolder_) for use where ever a xref:ROOT:how-antora-builds-urls.adoc#domain-relative[domain-relative URL] is required.

[#root-relative-site-url]
== Configure a root-relative site URL

A root-relative site URL value must start with a forward slash (_/products_).

.antora-playbook.yml
[source,yaml]
----
site:
  title: Docs Hosted Somewhere
  url: /products
----

You might use a root-relative site URL instead of an absolute site URL if identical sites must be published to or accessible via multiple domains or hostnames.
By using a root-relative value, you can take advantage of most of the benefits of assigning a site URL.
However, Antora deactivates any feature that depends on absolute site URLs, such as the sitemap and canonical URL tag, at runtime when the value assigned to `url` isn't absolute.

Any root-relative value assigned to the `url` key, except for a bare forward slash, is extracted by Antora and assigned to the xref:ROOT:how-antora-builds-urls.adoc#pathname[site pathname] for computing xref:ROOT:how-antora-builds-urls.adoc#domain-relative[domain-relative URLs].
If you want to set `url` to a root-relative site URL, but want the site pathname to be empty, set the value to a bare forward slash.

.antora-playbook.yml
[source,yaml]
----
site:
  title: The Docs
  url: /
----

[#when-should-the-site-url-be-set]
== When should the site URL be set?

An Antora site is designed to be viewable offline and from a local filesystem.
For this reason, the site URL is not required to build the site.

However, there are certain features related to publishing that require a URL, and in some cases an absolute URL.
When the site URL is not set, these features are automatically and silently disabled.

[#site-url-features]
=== Features that depend on the site URL

When the site URL is set to any allowable value, the following features are enabled:

* The `site-url` attribute is set on every AsciiDoc document.
* The `site.url` property is set in the UI model (the value of the `site.url` key in the playbook).
* The xref:ROOT:how-antora-builds-urls.adoc#pathname[site pathname] property, `site.path`, is set in the UI model.
* The 404 page is generated.
* The [.path]_robots.txt_ file is generated if `site.robots` is also defined in the playbook.
* xref:urls-redirect-facility.adoc[Redirects] include the site pathname (`site.path`), unless its assigned value is empty.
This does not affect the static redirect facility, which uses relative URLs.
* The link in the top-left corner of the navbar points to the site URL instead of a relative path (behavior specific to the default UI).

When the site URL is set to an absolute URL, the following additional features are enabled:

* The sitemap files are generated.
* The `page.canonicalUrl` is set in the UI model, which gets used by the default UI to create the canonical link tag in the head.

If the site URL is not set, all the aforementioned features are disabled.

[#subpath]
=== When should the site URL include a subpath?

The subpath of a site URL represents the location from the root of the domain where the site managed by Antora is located.
In other words, the site URL takes the visitor to the URL where the redirect for the site start page is located.
If your site is published to a subfolder of your domain then the site URL should include this path (e.g., _/path/to/subfolder_).

Antora uses the subpath from the site URL to construct absolute and domain-relative URLs to pages in your site.
This includes URLs in the sitemap (absolute URLs) as well as rewrite rules (domain-relative URLs).

Let's consider an example of how the subpath is used when creating a server redirect rule.
Assume the following conditions are true:

* The site is published to the [.path]_docs_ subfolder of the example.com domain.
* The page [.path]_new-page.adoc_ in the ROOT module of the versionless _component-a_ component defines the xref:page:page-aliases.adoc[page alias] [.path]_old-page.adoc_ (meaning [.path]_old-page.adoc_ was renamed to [.path]_new-page.adoc_).
* The xref:urls-redirect-facility.adoc[redirect facility] is set as `nginx`.
* You set the site `url` key to _\https://example.com_ (the incorrect value) in your playbook.

When you run Antora, it generates the following redirect rule:

.A redirect entry that does not includes a subpath
[listing]
----
/component-a/old-page.html /component-a/new-page.html 301!
----

Notice that the domain-relative URLs in the redirect rule don't include the leading `/docs` segment.
That means if you visit _\https://example.com/docs/component-a/old-page.html_, you are *not* redirected to the new page, because the rule won't match.
Let's fix that.

Edit your playbook and set the `url` key to `https://example.com/docs`.
Now when you run Antora, it generates the following redirect rule:

.A redirect entry that includes a subpath
[listing]
----
/docs/component-a/old-page.html /docs/component-a/new-page.html 301!
----

This time, the leading `/docs` segment is present in the domain-relative URLs.
Now, when you visit _\https://example.com/docs/component-a/old-page.html_, you are redirected to the new page.

It's important to include the path in the <<absolute-site-url,absolute site URL>> if your site is published to a sub-directory of your domain.
If you don't want to tie your site to a specific domain, assign a <<root-relative-site-url,root-relative site URL>> instead.
Either way, if you're publishing your site from a sub-directory of your domain, you should include the subpath when assigning a site URL to `url`.
