= UI Bundle URL and Start Path
:url-zip-file-format: https://en.wikipedia.org/wiki/Zip_(file_format)

The URL key (`url`) under the `bundle` key defines the location Antora should look to find a UI archive in {url-zip-file-format}[ZIP] format (i.e., UI bundle).
The key accepts a URL or a filesystem path.

[#remote-bundle]
== Fetch and load a remote UI bundle

When the value of `url` is a valid URL, Antora downloads and caches the ZIP archive on the first run.
On subsequent runs, Antora loads the bundle from the cache, if available.
This saves Antora from having to download the bundle each time you generate your site.

.Remote UI bundle
[source,yaml]
----
ui:
  bundle:
    url: https://repo.example.org/path/to/ui-bundle-1.0.0.zip
----

The value used in this example is the URL to Antora's default UI.

TIP: The bundle is cached based on the signature of the URL.
As long as the URL remains the same, and the `snapshot` key is not set to true, Antora continues to use the cached file.
If you want to force Antora to download a snapshot UI bundle again, pass the `--fetch` option to the CLI.
Another option is to remove the cached file.

[#snapshot]
== Use a remote UI bundle snapshot

If the URL of the UI bundle does not change, but the archive it points to does change, you need to mark the bundle as a snapshot.
This hint tells Antora to download the UI bundle again when the `--fetch` option is passed to the CLI.
Otherwise, Antora assumes the URL is permanent and does not download it again as long as it exists in the cache.

.Remote UI bundle marked as a snapshot
[source,yaml]
----
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
----

If you're using the default UI bundle, you should mark it as a snapshot.

[#local-bundle]
== Load a UI bundle from the filesystem

If the UI bundle is available locally, it can be referenced using an absolute or relative filesystem path.

.Relative UI bundle path
[source,yaml]
----
ui:
  bundle:
    url: ./../docs-ui/build/ui-bundle.zip
----

A relative path is automatically expanded to an absolute path using the following rules:

* If the first path segment is `~`, the path is resolved relative to the user's home directory.
* If the first path segment is `.`, the path is resolved relative to the location of the playbook file.
* If the first path segment is `~+`, or does not begin with an aforementioned prefix, the path is resolved relative to the current working directory.

Here's the path to the same UI bundle, but using an absolute path instead.

.Absolute UI bundle path
[source,yaml]
----
ui:
  bundle:
    url: /home/user/projects/docs-ui/build/ui-bundle.zip
----

[#start-path]
== Specify a UI start path

The `start_path` under the `bundle` subcategory is the relative path inside the bundle from where Antora should start reading files.
This key is useful when you're using a bundle that packages multiple UIs, which might be the case if the UI provides multiple themes (e.g., light, dark, etc.).

.Select UI from start_path
[source,yaml]
----
ui:
  bundle:
    url: /home/user/projects/docs-ui/build/ui-bundle-with-themes.zip
    start_path: dark
----

In this example, Antora will ignore all of the files in the UI bundle that fall outside the [.path]_dark_ directory.
