= Redirect Facility Key
:page-aliases: configure-redirect-facility.adoc
// URLS
:url-netlify-redirects: https://docs.netlify.com/routing/redirects/
:url-nginx-rewrites: https://nginx.org/en/docs/http/ngx_http_rewrite_module.html#return
:url-meta-tag: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

Antora will set up routing for start pages and page aliases according to the redirect facility you have specified.

By default, Antora generates a static HTML file for each page alias that redirects the visitor to the target page.
Antora also has the ability to generate web server-specific configuration files that leverage the web server's rewrite facility to handle the routing.

Antora derives these routes from the site and component version start pages as well as xref:page:page-aliases.adoc[page aliases] defined using the `page-aliases` attribute in the header of the target page.
The xref:page:page-aliases.adoc#target-page[target page] is the the page to which you're redirecting, which is also where page aliases are defined.
The xref:page:page-aliases.adoc#source-page[source page] is the alias page that's being redirected (i.e., the claimed page).

[#redirect-facility-key]
== redirect_facility key and its values

The playbook key `redirect_facility` is optional.
It can be configured in the playbook or via the xref:cli:options.adoc#redirect-facility[CLI] and accepts one of the following built-in values:

disabled::
No redirect file are generated.
gitlab::
A redirect file for GitLab Pages named [.path]_++_redirects++_ is generated and placed at the root of the published site.
httpd::
A redirect file for Apache httpd named [.path]_.htaccess_ is generated and placed at the root of the published site.
netlify::
A redirect file for Netlify named [.path]_++_redirects++_ is generated and placed at the root of the published site.
nginx::
A redirect file for nginx named [.path]_rewrite.conf_ is generated and placed at the location [.path]_.etc/nginx/rewrite.conf_ in the published site.
+
CAUTION: By default, nginx will not know to look for the file in this location.
You either need to move it to where nginx can find it or configure nginx to use it at this location.
[[static-value]]static::
(default) A static HTML file with the `http-equiv` meta element set to `refresh` is generated at the source page's URL.
The file provides a redirect notice and routes the source page URL to the target page URL.

Antora automatically assigns the value `static` to the `redirect_facility` key unless you explicitly configure it.

=== Configure the redirect facility from the playbook

The `redirect_facility` key is configured in the playbook under the `urls` key.

.antora-playbook.yml
[,yaml]
----
urls:
  redirect_facility: netlify
----

=== Configure the redirect facility from the CLI

The `redirect_facility` key can also be configured from the xref:cli:options.adoc[CLI].

 $ antora --redirect-facility netlify antora-playbook.yml

== Choosing a redirect facility configuration

How your site's URL redirects should be configured depends on the web server or service you use to serve your site.

If you use the default redirect facility, Antora will generate HTML pages that use the meta refresh feature of HTML to route the visitor to the target page (i.e., bounce page).
When you inspect the output of your site, you will find pages that end with [.ext]_.html_ that include a `<meta http-equiv="refresh">` tag inside a minimal HTML structure.
If you have specified a start page for your site, this will include a [.path]_index.html_ page at the root of your published site.

If you use any other redirect facility, Antora will not generate these bounce pages.
(In other words, don't expect to find the [.path]_index.html_ page at the root of your published site).
Instead, Antora relies on the web server to apply the rewrite rules that it generates.
For details about these rules and where they are written, see the sections below.

=== Generated redirect configuration for Netlify

{url-netlify-redirects}[Redirect rules for sites served by Netlify] are configured in a plain text file named [.path]_++_redirects++_.
When the assigned redirect facility value is `netlify`, Antora generates [.path]_++_redirects++_ and places it at the root of the generated site.
Each redirect rule is automatically calculated by Antora from the `page-aliases` attributes, and then the 301 HTTP status code is applied to each rule.
This means that each redirect is considered permanent.

.Antora generated _redirects file
....
/component/version/module/old-name.html /component/version/module/new-name.html 301!
....

The example output above shows a redirect rule that routes the URL for a renamed page to it's target page URL and the applied 301 HTTP status code.

=== Generated redirect configuration for GitLab Pages

{url-netlify-redirects}[Redirect rules for sites served by GitLab Pages] are configured in a plain text file named [.path]_++_redirects++_.
The format of this file is a modified version of the one for Netlify.
When the assigned redirect facility value is `gitlab`, Antora generates [.path]_++_redirects++_ and places it at the root of the generated site.
Each redirect rule is automatically calculated by Antora from the `page-aliases` attributes, and then the 301 HTTP status code is applied to each rule.
This means that each redirect is considered permanent.

.Antora generated _redirects file
....
/component/version/module/old-name.html /component/version/module/new-name.html 301 <1>
....
<1> Unlike the redirect file for the `netlify` redirect facility, the rule does not end with `!`.

The example output above shows a redirect rule that routes the URL for a renamed page to it's target page URL and the applied 301 HTTP status code.

[#nginx]
=== Generated redirect configuration for Nginx

Antora generates an {url-nginx-rewrites}[Nginx rewrite configuration file] named [.path]_rewrite.conf_ and places it in the generated site at [.path]_.etc/nginx/rewrite.conf_.

.Antora generated rewrite.conf
....
location = /component/version/module/old-name.html { return 301 /component/version/module/old-name.html; }
....

The example output above shows a redirect rule with a 301 HTTP status code that permanently routes the URL for a renamed page to it's target page URL.

=== Generated static HTML refresh pages

The `static` redirect value is useful for sites deployed on services, such as GitLab Pages and GitHub Pages, that don't accept or provide access to URL redirection configuration files.
This setting is also helpful when you build a site on your local machine to test your `page-aliases`.

Antora generates a static HTML refresh page for each aliased source page that redirects a visitor to the corresponding target page.
Each refresh page contains:

. The canonical URL of the xref:page:page-aliases.adoc#target-page[target page].
. The `http-equiv` meta attribute assigned the value `refresh`.
. The `content` meta attribute assigned the value `0` and the URL of the relative target page that the visitor will be redirected to.
The `0` indicates that the visitor will be redirected to the target page in 0 seconds.
. A redirect notice, letting the visitor know that the xref:page:page-aliases.adoc#source-page[source page] no longer exists and providing a link to the target page.

.Generated static refresh page for old-name.html that redirects to new-name.html
[,html]
....
<!DOCTYPE html>
<meta charset="utf-8">
<link rel="canonical" href="https://base-url.com/component/version/module/new-name.html">
<script>location="new-name.html"</script>
<meta http-equiv="refresh" content="0; url=new-name.html">
<meta name="robots" content="noindex">
<title>Redirect Notice</title>
<h1>Redirect Notice</h1>
<p>
  The page you requested has been relocated to
  <a href="new-name.html">https://base-url.com/component/version/module/new-name.html</a>.</p>
....
