= Add Event Listeners
:url-event-emitter: https://nodejs.org/api/events.html#events_class_eventemitter

The bulk of the work of an Antora extension is done by the event listeners.
An event listener is a function that's called whenever an event it's listening for is emitted.
Any value returned by the listener is ignored.
The register function is responsible for associating these listener functions with particular events.
It does so by passing the event name and the listener function to the `on` method of the generator context, called adding a listener.
The xref:generator-context-reference.adoc[API of the generator context] follows that of a Node.js {url-event-emitter}[EventEmitter^].

Let's build on the extension we have defined by updating it to add an event listener.
We'll listen for the `playbookBuilt` and `sitePublished` events, which are the first and last events fired by the generator.
This gives us the opportunity to roughly measure how long it took to generate and publish the site.

.time-generation-extension.js
[#ex-listen,js]
----
include::example$time-generation-extension.js[]
----

In <<ex-listen>>, we use the `on` method of the generator context to add two listeners, one for when the `playbookBuilt` event is fired and one for when the `sitePublished` event is fired.
The `on` method returns the generator context, so we can use it to chain calls, as show in the previous example.

By default, listeners are invoked in the order they are added.
To guarantee our timer starts before listeners from other extensions are called, our `playbookBuilt` listener should be called before other listeners of the `playbookBuilt` event and our `sitePublished` listener should be called after other listeners of the `sitePublished` event.
There are two changes we must make to get this to work.

First, we can use the `prependListener` method as an alternative to `on` to add the `playbookBuilt` listener before other listeners that have already been associated with that event.

.time-generation-extension.js
[,js]
----
include::example$better-time-generation-extension.js[]
----

Second, we should list our extension last in the playbook.
Taking these two steps ensures our timer runs around all other listeners.

TIP: If you want to time a specific stage of the generator, you can update this extension to listen to xref:generator-events-reference.adoc[other generator events].

The EventEmitter API, which the generator context inherits, also allows listeners to be retrieved, removed, and added again.
That opens up the possibility that one extension can rearrange listeners added by other extensions, if the need arises.

To do something more interesting than time the execution and print messages to the console, we need to xref:use-context-variables.adoc[use context variables].
Let's learn how that's done next.
[
