[#checklist]
== Upgrade from Antora 2.3 to Antora {page-component-version} checklist
// tag::new[]
*Antora 2 is EOL*.
If you're currently using Antora 2, you may need to make the following changes to your documentation system before upgrading to Antora {page-component-version}.
If you're already using Antora 3.0, skip this section and go to xref:install:upgrade-antora.adoc#node[Upgrade Node.js].

Are you using an active LTS version of Node.js?::
We recommend upgrading to the {url-node-releases}[latest active long term support (LTS) release of Node].
Antora 3 officially supports Node.js 16 LTS and Node.js 18 LTS.
Antora 3 doesn't support Node.js versions that have reached end of life (EOL).
See xref:install:upgrade-antora.adoc#node[Upgrade Node.js] for instructions.

Have you updated your AsciiDoc syntax and Asciidoctor extensions to comply with the newest patch release of Asciidoctor.js 2.2?::
Antora 3 dropped support for Asciidoctor.js 1.5.9 (which provides Asciidoctor 1.5.8) and now depends on the latest patch version of Asciidoctor.js 2.2 (which provides Asciidoctor 2.0.x).
Asciidoctor 2 introduces a few substantive changes to existing features that may impact your documentation source content or UI.
See xref:ROOT:asciidoctor-upgrade-notes.adoc[] to learn about the affected features and the suggested actions you should take before upgrading to Antora 3.

Are you linking to attachment files?::
Using the AsciiDoc link macro (`+link:[]+`) and `+{attachmentsdir}+` attribute reference in the target value to reference an attachment has been deprecated in Antora 3.
Replace the link macro with the xref macro and use the attachment's resource ID to reference it.
See xref:page:attachments.adoc[] and xref:navigation:reference-resources.adoc[] to learn about the `attachment$` family coordinate and for usage examples.

Are any of your component versions unversioned?::
We've deprecated the use of the value `master`, when assigned to the `version` key, to identify an unversioned component.
In Antora 3, assign the tilde (`~`) to the `version` key in a component version's [.path]_antora.yml_ file to specify it as unversioned.
See xref:ROOT:component-with-no-version.adoc[] to learn more.

Make sure you're using file extensions when cross referencing pages or assigning `page-aliases` values.::
If the _.adoc_ file extension was missing from the resource ID in an xref macro or the value assigned to a `page-aliases` attribute, Antora 2 would automatically add _.adoc_ to the resource ID at runtime.
This fallback mechanism has been deprecated because the xref macro can now reference other non-AsciiDoc resources.
Review the resource IDs in your xrefs and `page-aliases` attributes to ensure the _.adoc_ extension is specified.

Are you depending on the default branches pattern in your playbook?::
The previous default branches pattern, `[master, v*]`, has been deprecated and replaced with `[HEAD, v{0..9}*]`.
It's unlikely this will cause a change when using remote repositories.
For local repositories, it may result in the worktree being used in cases it wasn't previously.

Do you use the antora-lunr add-on to integrate Lunr into your site?::
The antora-lunr add-on was designed for Antora 2 and is a community-maintained project.
In Antora 3, antora-lunr has been replaced by the https://gitlab.com/antora/antora-lunr-extension[Antora Lunr extension] (package: `@antora/lunr-extension`), which is an official Antora project.
This extension uses the new extension facility in Antora 3 to integrate Lunr into your site without having to resort to using a custom site generator.
We encourage you to migrate from antora-lunr to the Antora Lunr Extension when upgrading to Antora 3.

Do you use or maintain a custom site generator?::
In Antora 3, the site generator must declare the `@antora/logger` package as a dependency.
The CLI resolves the logger relative to the site generator.
If it cannot find it there, it will fall back to the logger provided by the CLI.
This may result in Antora configuring the wrong logger, which will result in the user to see a warning about the logger not being configured.
+
Also note that the recommended signature of the `generateSite` function has changed.
The function now accepts a single parameter, the playbook.
The old signature is still supported, but using it will result in the playbook being built a second time.
+
The site generator should also depend on the `@antora/file-publisher` package instead of `@antora/site-publisher`, though technically this isn't required.

Do you use a custom git credential manager?::
Isomorphic-git no longer includes the `cores` (plugin) API, so the call `git.cores.create('antora').set('credentialManager', customCredentialManager)` is going to fail.
Antora still honors the `cores` API, but the call to register the credential manager is now responsible for creating it (since it runs before Antora loads).
Refer to xref:playbook:private-repository-auth.adoc#custom[Configure a custom credential manager] for the latest instructions.

ifeval::["{route}" == "New"]
See xref:install:upgrade-antora.adoc[Upgrade Antora] for instructions when you're ready to upgrade to Antora 3.

== Antora 2.3 EOL

Antora 2.3 reached end of life (EOL) as of February 25, 2022.

endif::[]
// end::new[]
