= Antora page- Attributes

Attributes that are prefixed with `page-` are available to the Antora pipeline and passed to the xref:antora-ui-default::templates.adoc#template-variables[UI model and templates].

== Define a built-in page- attribute

Antora provides a few built-in `page-` attributes that accept user-defined values, such as `page-aliases` and `page-layout`.
The attribute is set by entering its name in an xref:attributes.adoc#attribute-entry[attribute entry] in the header of the page.
The value you assign to the attribute must be offset from the closing colon (`:`) by at least one space.

[source]
----
= Page Title
:page-aliases: admin:forgot-password.adoc
----

The type of value a built-in `page-` attribute accepts depends on the attribute.
For instance, the xref:page-aliases.adoc[page-aliases attribute] only accepts page IDs in a comma-separated list.

WARNING: Antora automatically sets a number of read-only `page-` attributes at runtime that it derives from the playbook and component version descriptor keys.
The read-only `page-` attribute names listed in the xref:ROOT:environment-and-page-attributes.adoc[Page and environment attribute reference] are reserved.
Don't unset or override them in the header of a page.

[#custom-attribute]
== Define a custom page- attribute

You can also create custom `page-` attributes.
Custom `page-` attributes are often used to provide site metadata about the page to the UI templates.

[source]
----
= Page Title
:page-level: Intermediate
:page-team: SecOps
----

The attribute is defined using an attribute entry.
It must have a user-defined name that's prefixed with `page-`.
The name cannot contain dots (`.`) or blank spaces.
Custom `page-` attributes accept string values.
