= Attachments
:page-aliases: asciidoc:link-attachment.adoc
:family: attachment
:coordinate: attachment$

Attachments are resources, such as PDFs or the ZIP archives of sample projects.
Attachment files are stored in an xref:ROOT:attachments-directory.adoc[_attachments_ family directory].

== Attachment resource IDs and xref macros

The xref:resource-id.adoc[resource ID of an attachment] must always specify its family coordinate (`{coordinate}`) when it's referenced.
An attachment can be cross referenced from pages, other resources, and navigation files using an xref:xref.adoc#xref-macro[AsciiDoc xref macro].

<<ex-base>> shows the structure of an xref macro with an {family}'s fully qualified resource ID.

.Xref and attachment resource ID syntax
[#ex-base,subs=attributes+]
----
xref:version@component:module:{coordinate}file-coordinate-of-attachment.ext[optional link text]
----

When referencing an attachment, the xref macro is structured and behaves much like when it's assigned the resource ID of a page, with three differences:

* The attachment's resource ID must specify the `{coordinate}` family coordinate, otherwise Antora will assume the value is that of a page at runtime.
* A fragment (element ID) can't be appended to the end of the attachment's resource ID.
* An attachment doesn't have default reference text.
If you don't specify link text in the xref macro, the URL of the published attachment is displayed as the link text in the current page.

How many coordinates of the attachment's resource ID you need to specify as the value of the xref macro depends on the component version and module of the current page in relation to the attachment.

== Create a link to an attachment

Let's break down the xref macro and resource ID coordinates you need to create a link to an {family} from a page.
The following steps assume that the target {family} and xref:xref.adoc#current[current page] belong to the same component version and module.
Therefore, the resource ID of the target {family} only requires the family coordinate, `{coordinate}`, and family-relative directory path of the {family} file.

. In the flow of your content, enter the name of the macro followed by one colon, `xref:`.
+
[listing,subs=+quotes]
----
See the **xref:**
----

. Enter the resource ID of the target {family} file.
The resource ID must specify the `{coordinate}` family coordinate.
+
[listing,subs="attributes+,+quotes"]
----
See the xref:**{coordinate}filename.ext**
----

. Directly after the attachment's file extension, enter an opening square bracket (`[`), followed by optional link text, and then a closing square bracket (`]`).
+
[listing,subs="attributes+,+quotes"]
----
See the xref:{coordinate}filename.ext**[optional link text]** for more options.
----

== Link text for attachments

If you don't specify link text in an xref macro that references an attachment, Antora displays the URL of the attachment as the link in the published page.

.Attachment xref with no link text
[source#ex-no-text]
----
Download xref:attachment$practice-project.zip[] to try it out!
----

The result of <<ex-no-text>>, would be display as shown below.

....
Download https://docs.example.com/component/version/module/_attachments/practice-project.zip to try it out!
....

You can specify link text by entering it between the square brackets of the xref macro.

.Attachment xref with link text
[source#ex-text]
----
Download xref:attachment$practice-project.zip[The Sample Project] to try it out!
----

You can also create links to attachments in xref:navigation:reference-resources.adoc[navigation files], image macros, and partials.
