= AsciiDoc Attributes in Antora

Like the AsciiDoc processor, Antora uses AsciiDoc document attributes (herein _attributes_) to circulate information in and out of pages.
These attributes are used to toggle or configure processing settings, control behavior and styles of the output, pass metadata from the source to the output, and pass down information about the page to the content, among a variety of other uses.

In general, there are two categories of attributes: built-in and custom.
Built-in attributes are those that have a reserved name and predefined purpose.
Some built-in attributes are designed to be set, while others are intended to be read-only.
You can also define custom attributes that work in a similar way.

This page introduces these two catagories of attributes, explains how attributes are defined in a page, and refers you to pages that cover the built-in attributes in more depth.

== Built-in attributes

[.term]*Built-in attributes* are xref:define-and-modify-attributes.adoc[AsciiDoc document attributes] that either pass information to the page or provide a way for the author to toggle or configure behavior.
Some built-in attributes are read-only, while others are meant to be modified.
These built-in attributes have reserved names and serve a special, predefined purpose.

Attributes designed to be modified may be set from the CLI, in the playbook, in the componen version descriptor, or in the page.
If the attribute is set in the page, it must be defined in the page header using an <<attribute-entry,attribute entry>>.

Many modifiable built-in attributes have a restricted set of accepted values.
These attributes usually do two things; they toggle a behavior on or off, and they further accept information that alters how the output is generated.
For example, the `xrefstyle` attribute controls the style of the linked text of internal xrefs (e.g., basic, short, or full).

include::ROOT:partial$dont-use-these-attributes.adoc[]

The AsciiDoc processor already defines a plethora of built-in attributes.
Antora introduces xref:intrinsic-attributes.adoc[additional built-in attributes] that are only relevant in the Antora environment.
Several of these configure the AsciiDoc processor to work in the Antora environment.
But most of them are xref:page-attributes.adoc[page attributes], which are attributes prefixed with `page-`.
Page attributes are special in that they get promoted to the page UI model so they can be accessed from the xref:antora-ui-default::templates.adoc#template-variables[UI templates].

Page attributes open up the door of passing metadata to the UI template using custom attributes.

== Custom attributes

[.term]*Custom attributes* are xref:define-and-modify-attributes.adoc[AsciiDoc document attributes] defined by the author.
You may be familiar with using custom attributes in AsciiDoc to store reusable content, such as a URL or product name.
The value of a custom attribute can then be used within the page (or across pages, depending on where it's defined) using an attribute reference.
Custom attributes work the same way in Antora.

Where things get interesting is when a custom attribute is defined as a xref:page-attributes.adoc[page attribute].
A custom page attribute allows the author to pass additional information about a page to the UI templates (thus not limited to the page itself).

Custom attributes can be defined from the CLI, in the playbook, in the component version descriptor, or in header of a page using an <<attribute-entry,attribute entry>>.
See xref:define-and-modify-attributes.adoc#custom-attribute[Define a custom AsciiDoc attribute] and xref:page-attributes.adoc#custom-attribute[Define a custom page attribute] to learn how to define your own custom attributes.

[#attribute-entry]
== What's an attribute entry?

Before you can use a modifiable built-in attribute or custom attribute, you have to declare it.
An [.term]*attribute entry* is the primary mechanism for activating the attribute and assigning it a value in a page.
It's like a global variable assignment for AsciiDoc.

An attribute entry consists of two parts: a *name* and a *value*.
Each attribute entry must be entered on its own line in a page header.
An attribute entry starts with an opening colon (`:`), directly followed by the attribute's name, and then a closing colon (`:`).
This activates, or [.term]*sets*, the attribute so you can use it in your page.

[source]
----
= Page Title
:name-of-an-attribute: <1>
----
<1> The attribute's name is directly preceded with a opening colon (`:`) and directly followed by a closing colon (`:`).

In many cases, you explicitly assign a value to an attribute by entering information after its name in the attribute entry.
The value must be offset from the closing colon (`:`) by at least one space.

[source]
----
= Page Title
:name-of-an-attribute: value of the attribute <1>
----
<1> An explicitly assigned value is offset from the closing colon (`:`) by at least one blank space.
At the end of the value, press kbd:[Enter].

[[boolean]]
Some built-in AsciiDoc attributes don't require a value to be explicitly assigned in an attribute entry because they're a boolean attribute or have a default value.

[source]
----
= Page Title
:name-of-an-attribute: <1>
----
<1> If you don't want to explicitly assign a value to the attribute, press kbd:[Enter] after the closing colon (`:`).

The values of built-in boolean attributes are always blank because their only accepted value is an _empty string_.
Other built-in attributes may have a default value.
If you set a built-in attribute and leave its value blank, Antora assigns the default value (if it has one) to the attribute at processing time.

TIP: AsciiDoc document and page attributes can also be xref:ROOT:component-attributes.adoc[scoped to a component version] or xref:playbook:site-attributes.adoc[scoped to a whole site].
