= Add Block Images
:colons: ::

On this page, you'll learn:

* [x] The structure of the AsciiDoc block image macro.
* [x] How to insert a block image using its resource ID.

== AsciiDoc block image macro

An AsciiDoc block image macro is used to embed the source file of an image into a partial or page.
The block image macro accepts the xref:resource-id.adoc[Antora resource ID] of PNG, JPG, SVG, and GIF (static and animated) image files as a value.

When Antora runs, the image file referenced by the block image macro is embedded and displayed as a discrete element in the published page.
For example, the SVG image below this paragraph is embedded in this page using the block image macro.

image::console.svg[]

=== Block image macro structure

<<ex-block-base>> shows the structure of a block image macro.

.Block image macro
[#ex-block-base]
----
This is a paragraph.

image::resource-id-of-target-image.ext[optional attribute,optional attribute] <.>

This is another paragraph.
----
<.> A block image is designated by two colons (`::`) after the macro name.
It's preceded by an empty line, entered on a line by itself, and then followed by an empty line.

At a minimum, a block image macro consists of the macro's prefix (`image::`), the resource ID of the target image, and a set of square brackets (`[]`).
include::image-resource-id-examples.adoc[tag=target-current-def]

Each part of the block image macro shown in <<ex-block-base>> is described in more detail below.

image{colons}::
An block image macro begins with the macro's name, `image`, followed by two colons (`::`).

resource ID of target image::
The image macro accepts the resource ID of an image source file as its value.
The value is entered directly after the second colon that follows the macro's name (`image::`).
How many of the target image's xref:resource-id-coordinates.adoc[resource ID coordinates] you need to specify depends on the component version and module of the target image in relation to the current page.
When referencing an image from an image macro, you don't need to include the `image$` family coordinate in the target image's resource ID.
It's applied automatically at runtime.

[#attribute]
[optional attribute,optional attribute]::
The block image macro is completed with a set of square brackets (`[]`) at the end of the target image's resource ID.
You can leave the brackets empty, or assign one or more optional attributes as a comma-separated list inside the square brackets.

The next section, <<insert-image>>, explains how to set up an block image macro step-by-step.

[#insert-image]
== Embed a block image

Let's break down the block image macro and resource ID coordinates you need to insert an image (the <<target,target image>>) into a page (the <<current,current page>>) using the block image macro.

. In your IDE or text editor, open the page where you want to insert an image.
For this exercise, we've opened the file [.path]_satellites.adoc_.
[.path]_satellites.adoc_ is the current page.
. In [.path]_satellites.adoc_, let's embed the block image [.path]_console.svg_.

. At the beginning of a new line, enter the macro's name followed by two colons, `image::`.
Make sure there is a blank line between the previous element, such as a paragraph or source block, and the line where you place the image macro.
+
.satellites.adoc (current page)
[listing,subs=+quotes]
----
After scanning your badge, you should see this screen.

**image::**
----

. Enter the resource ID of the target image file directly after the two colons.
In this example, both [.path]_console.svg_ and [.path]_satellites.adoc_ belong to the same component version and module and the target image is stored at the root of the [.path]_images_ family directory.
Therefore, only the filename and extension of [.path]_console.svg_ needs to be assigned as the value of the block image macro.
+
--
.satellites.adoc (current page)
[listing,subs=+quotes]
----
After scanning your badge, you should see this screen.

image::**console.svg**
----

Notice that the resource ID for [.path]_console.svg_ doesn't include its family coordinate.
Antora automatically applies the `image$` family coordinate to a resource ID assigned to an image macro.
--

. Directly after the resource ID of the target image, enter an opening square bracket (`[`) and then a closing square bracket (`]`).
+
--
.satellites.adoc (current page)
[listing,subs=+quotes]
----
After scanning your badge, you should see this screen.

image::console.svg**[]**
----

We didn't apply any optional attributes to the block image macro in this example; however, you can specify one or more attributes as a comma-separated list inside the square brackets.
--

. Press kbd:[Enter] twice after the last square bracket (`]`) to insert a new line after the image macro.
+
.satellites.adoc (current page)
[listing]
----
After scanning your badge, you should see this screen.

image::console.svg[]

Enter the satellite position after the prompt.
----

That's it!
You've finished inserting the target image ([.path]_console.svg_) into the current page ([.path]_satellites.adoc_) using the AsciiDoc block image macro.

== Learn more

To learn how to embed images that belong to other modules, docs components, and versions, see xref:image-resource-id-examples.adoc[Image resource ID examples].
