= Define and Modify Attributes
:xrefstyle: short
:listing-caption: Example

[#set-attribute]
== Set a built-in attribute

Let's activate the AsciiDoc attribute named `sectanchors`.
The attribute is set by entering its name in an xref:attributes.adoc#attribute-entry[attribute entry] in the header of the page.

.Set a built-in attribute
[source]
----
= Page Title
:sectanchors: <1>
----
<1> The attribute is set in page header by directly preceding its name, `sectanchors`, with an opening colon (`:`) and directly following it with a closing colon (`:`).

When set, `sectanchors` adds an anchor to the left of each xref:asciidoc:section-headings.adoc[section title].
`sectanchors` is a xref:attributes.adoc#boolean[boolean attribute], so its value is an _empty string_.

== Assign a value to a built-in attribute

In the next example, let's assign a value to a built-in AsciiDoc attribute.
The attribute `xrefstyle` has three built-in values it can accept, `short`, `full`, and `basic`.

[source]
----
= Page Title
:xrefstyle: short <1>
----
<1> Set `xrefstyle` in the page header and assign it the value `short`.
Explicit values must be offset from the closing colon (`:`) by at least one space.

When the `short` value is assigned to `xrefstyle`, any in-page references to blocks with anchors will display the blocks`' label and number, e.g., _Listing 1_, if no link text is specified in the reference.

include::ROOT:partial$dont-use-these-attributes.adoc[]

[#custom-attribute]
== Define a custom attribute

Custom attributes often store frequently used text and URLs.
They're then referenced throughout the page by simply entering their name (instead of repeatedly typing the text or URLs).
Before they can be referenced, custom attributes must have a user-defined name and be assigned a value.

[#naming-rules]
The attribute's name must:

* be at least one character long,
* begin with a word character (A-Z, a-z, 0-9, or _), and
* only contain word characters and hyphens, meaning the name cannot contain a dot (`.`) or a space.

Although uppercase characters are permitted in an attribute name, the name is automatically converted to lowercase before being stored.
A best practice is to only use lowercase letters in the name and avoid starting the name with a number.

Attribute values can:

* be any inline content, and
* contain line breaks, but only if an explicit line continuation (`+`) is used.

In <<ex-custom>>, a custom attribute's name and value are defined using an xref:attributes.adoc#attribute-entry[attribute entry].

[#ex-custom]
.Define a custom attribute using an attribute entry
[source]
----
= Page Title
:url-repo: https://gitlab.com/antora/demo/docs-site
----

Now, you can reference the attribute wherever needed throughout the page by entering its name inside a set of curly braces (`+{attribute-name}+`).
You can see another example of a custom attribute being used to replace a complex URL in xref:asciidoc:external-urls.adoc#create-custom-attribute[Create an attribute for a URL].

== Unset an attribute

Built-in and custom attributes can be [.term]*unset*, that is, turned off, with a leading or trailing bang symbol (`!`) added to its name in an attribute entry.

[source]
----
= Page Title
:!sectanchors:
:table-caption!:
----

Once unset, an attribute's behavior and value are no longer available to the page.
