= Include an Example
:article: an
:family: example
:coordinate: example$
:ext: .ext
:page-aliases: asciidoc:include-example.adoc
// URLs
:url-tags: {url-asciidoc}/directives/include-tagged-regions/
:url-leveloffset: {url-asciidoc}/directives/include-with-leveloffset/
:url-indent: {url-asciidoc}/directives/include-with-indent/

An example can be inserted into any page or partial in your site using the AsciiDoc include directive and the example's resource ID.

== Insert an example into a page

include::partial$include-directive.adoc[]

== Include an example from the same module

When the target example file and the current page belong to the same module, you only need to enter the family and file coordinates in the resource ID.

.current-page.adoc
----
\include::example$helloworld.java[]
----

== Include an example from another module

When the target example file and current page belong to different modules of the same component version, enter the example's module, family, and file coordinates in the resource ID.

.current-page.adoc
----
\include::ROOT:example$output/query-max.json[]
----

== Include an example from another component

When the target example file and the current page belong to different docs components, enter the example's version, component, module, family, and file coordinates in the resource ID.

.current-page.adoc
----
\include::4.5@uml:admin:example$config.js[]
----

Don't specify the version coordinate if you want the page to always reference the latest version of the example.

.current-page.adoc
----
\include::uml:admin:example$config.js[]
----

//== Include a tagged region from an example

== Learn more

* xref:include-a-partial.adoc[Include a partial]
* xref:include-a-page.adoc[Include a standard page]
* xref:resource-id.adoc[Resource IDs]

.*AsciiDoc and Asciidoctor resources*
* {url-tags}[Select regions of content with tags^]
* {url-indent}[Normalize block indentation with indent^]
* {url-leveloffset}[Offset section headings with leveloffset^]
