= Include a Page
:family: page
:coordinate: page$
:ext: .adoc
:page-aliases: asciidoc:include-page.adoc
// URLs
:url-include: {url-asciidoc}/directives/include/
:url-tags: {url-asciidoc}/directives/include-tagged-regions/
:url-leveloffset: {url-asciidoc}/directives/include-with-leveloffset/

In Antora, the AsciiDoc include directive is configured to include another page or portion of a page into the current page.
You can include a page from anywhere in the site, including pages from other docs components.

== Include a page into another page

<<ex-base>> shows the structure of an include directive with a {family}'s fully qualified resource ID.

.Include directive and resource ID syntax
[#ex-base,subs=attributes+]
----
\include::version@component:module:filename{ext}[]
----

Let's break down the AsciiDoc syntax and resource ID coordinates you need to include a {family} resource into a page.
The following steps assume that the target {family} and xref:resource-id.adoc#current-page[current page] belong to the same component version and module.
Therefore, the resource ID of the target {family} only requires the family-relative path of the {family} file.

. On a new line, enter the name of the directive followed by two colons, `include::`.
+
[listing,subs=+quotes]
----
**include::**
----

. Enter the resource ID of the target {family} file.
+
--
[listing,subs="attributes+,+quotes"]
----
include::**filename{ext}**
----

You can use the `{coordinate}` family coordinate in the resource ID if you prefer, but it isn't required when including a page.
The include directive assumes the family coordinate is `{coordinate}` when it isn't specified.
--

. Close the directive with a set of square brackets (`+[]+`).
+
[listing,subs="attributes+,+quotes"]
----
include::filename{ext}**[]**
----

. The brackets can contain an optional list of attributes.
The attributes are entered as key-value pairs separated by commas.
+
[listing,subs="attributes+,+quotes"]
----
\include::filename{ext}[**attribute,attribute**]
----

Antora supports filtering the lines of an include file by either line numbers using the `lines` attribute or tags using the `tag` or `tags` attributes.
Filtering by line numbers takes precedence.
See the {url-include}[AsciiDoc include directive documentation] for full details about the `lines`, `tag`, and `tags` syntax.

== Include a page using a relative path

. On a new line, enter the name of the directive followed by two colons.
+
[listing,subs=+quotes]
----
*include::*
----

. Next, enter the relative path of the target page in the target slot.
A relative path include is resolved from the current page (not the root of the pages family).
The relative path must be prefixed with `./`.
+
--
[listing,subs=+quotes]
----
include::**./relative-page-filename.adoc**
----

CAUTION: You may find that the relative path works without this prefix, but that could change in the future.
--

. Close the directive using a set of square brackets (`[]`).
+
[listing,subs=+quotes]
----
include::./relative-page-filename.adoc**[]**
----

. The brackets may contain an optional list of attributes.
Attributes are entered as key-value pairs separated by commas.
+
--
[listing,subs=+quotes]
----
\include::./relative-page-filename.adoc[**attribute,attribute**]
----

All the attributes (e.g., `lines`, `tags`, `leveloffset`, `indent`) on the include directive are supported.
--

== Learn more

* xref:page-partial.adoc[page-partial attribute]
* xref:resource-id.adoc[Resource IDs]
* xref:include-a-partial.adoc[Include a partial]
* xref:include-an-example.adoc[Include an example]

.*AsciiDoc and Asciidoctor resources*
* {url-tags}[Select regions of content with tags^]
* {url-leveloffset}[Offset section headings with leveloffset^]
