= Pages
:keywords: Antora file, Antora site page

On this page, you'll learn:

* [x] The difference between a standard and a partial page.
* [x] How Antora handles an [.path]_index.adoc_ file stored in the ROOT module of a component.

Antora generates site pages from AsciiDoc files.
AsciiDoc files are text files marked up with the xref:asciidoc:asciidoc.adoc[AsciiDoc syntax] and saved with the file extension `.adoc`.

Whether Antora automatically processes an AsciiDoc file depends on where it is stored in a documentation component.

[#standard]
== Standard page

Antora generates one site page for each AsciiDoc file located in the [.path]_pages_ directory of a module.
These files are converted to individual HTML pages automatically.
Another way to think about this: one AsciiDoc file in equals one HTML page out.

my-page.adoc => my-page.html

While all standard pages are automatically included in your site, if you want visitors to locate and go to a specific page using a component navigation menu, then you must add a cross reference (`xref`) to that page in the appropriate xref:navigation:index.adoc[navigation source file].
If you don't want to include a page in a component menu, visitors will still be able to find it using search tools and through links to it on other pages, and in some scenarios, through dropdown menus such as the page version selector.

Learn more:

* xref:create-standard-page.adoc[Create a standard page]
* xref:asciidoc:include-page.adoc[Insert content from a standard page into another page]
* xref:ROOT:pages-directory.adoc[The _pages_ directory]
* xref:navigation:link-syntax-and-content.adoc#page[Add a page xref to a navigation file]

[#partial]
== Reusable partial pages

Partials are usually AsciiDoc source files (_.adoc_) that contain content snippets, such as common descriptions, terminology, or reference tables, that you plan to insert in multiple pages.
They may also be reusable UML, STEM, or CSV/TSV content.
The source files for partials are stored in a [.path]_partials_ directory.
Partials aren't converted to HTML by Antora automatically.
Instead, they must be referenced by an xref:asciidoc:include-partial.adoc[include directive] in a standard page.

Partials are good for storing snippets of content, such as concept definitions or project introductions, that you reuse in one or more standard pages.
When you change the content in a partial, those changes will be disseminated to all of the standard pages where you embedded that partial with an include directive.

Learn more:

* xref:ROOT:partials-directory.adoc[The _partials_ directory]
* xref:asciidoc:include-partial.adoc[Insert a partial into a standard page]

== Component version index page

If a file named [.path]_index.adoc_ exists in the ROOT module of a component, Antora will automatically set this page as the start page of that component version.

component:ROOT:index.adoc => site.com/component/index.html

Learn more:

//* Create a component index page
* xref:ROOT:component-start-page.adoc[Specify a component version's start page]

//* html extension options
* xref:ROOT:root-module-directory.adoc[The ROOT module directory]

// TIP: see the html strategies for dropping the html and index for URLs

// Site index page
