= Pages
:keywords: Antora file, Antora site page

On this page, you'll learn:

* [x] The difference between a standard and a partial page.
* [x] How Antora handles an [.path]_index.adoc_ file stored in the ROOT module of a component.

Antora generates site pages from AsciiDoc files.
AsciiDoc files are text files marked up with the xref:asciidoc:asciidoc.adoc[AsciiDoc syntax] and saved with the file extension `.adoc`.

Whether Antora automatically processes an AsciiDoc file depends on where it is stored in a documentation component.

[#standard]
== Standard page

Antora generates one site page for each AsciiDoc file located in the [.path]_pages_ directory of a module.
These files are converted to individual HTML pages automatically.
Another way to think about this: one AsciiDoc file in equals one HTML page out.

my-page.adoc => my-page.html

While all standard pages are automatically included in your site, if you want visitors to locate and go to a specific page using a component navigation menu, then you must add a cross reference (`xref`) to that page in the appropriate xref:navigation:index.adoc[navigation source file].
If you don't want to include a page in a component menu, visitors will still be able to find it using search tools and through links to it on other pages, and in some scenarios, through dropdown menus such as the page version selector.

Learn more:

* xref:create-standard-page.adoc[Create a standard page]
* xref:asciidoc:include-page.adoc[Insert content from a standard page into another page]
* xref:ROOT:modules.adoc#pages-dir[The _pages_ directory]
* xref:ROOT:component-structure.adoc[Documentation component overview]
* xref:navigation:link-syntax-and-content.adoc#page[Add a page xref to a navigation file]

[#partial]
== Reusable partial pages

Partials are AsciiDoc files located in a [.path]_partials_ directory.
// (or [.path]_pages/_partials_).
These files are *not* converted to HTML by Antora automatically.
Instead, they must be referenced by an xref:asciidoc:include-partial.adoc[include directive] in a standard page.

Partials are good for storing snippets of content, such as concept definitions or project introductions, that you reuse in one or more standard pages.
When you change the content in a partial, those changes will be disseminated to all of the standard pages where you embedded that partial with an include directive.

Learn more:

//* Create a partial
* xref:ROOT:modules.adoc#partials-dir[The _partials_ directory]
* xref:asciidoc:include-partial.adoc[Insert a partial into a standard page]
* xref:ROOT:component-structure.adoc[Documentation component overview]

See also <<#implicit>>

== Component index page

If a file named [.path]_index.adoc_ exists in the ROOT module of a component, Antora will automatically set this page as the start page of that component.

component:ROOT:index.adoc => site.com/component/index.html

Learn more:

//* Create a component index page
* xref:ROOT:component-descriptor.adoc#start-page-key[Use another page to act as a component's start page]

//* html extension options
* xref:ROOT:modules.adoc#root-dir[The ROOT directory]

// TIP: see the html strategies for dropping the html and index for URLs

// Site index page

[#implicit]
== Implicit and explicit hidden and non-published pages

* Any file with name starting with '.' will be ignored

* Any file with name starting with '_' will not be generated but xref:asciidoc:include-page.adoc[will be available for inclusion]. 

* Similarly, any file with the asciidoc attribute `:page-publishable: false` will not be generated but xref:asciidoc:include-page.adoc[will be available for inclusion].

Note that the same effect as a partial page can be produced from a regular page by starting the file name with `_` or including the asciidoc attribute `:page-publishable: false`. 
Unlike for an explicit partial, an inclusion of such a page will not need the `partial$` family indication.

[#multiple]
== Multiple appearances of a single page

As noted earlier, Antora works by one AsciiDoc file in equals one HTML page out.

my-page.adoc => my-page.html

The navigation sidebar is generated from the page, not the page from the navigation.  Therefore it does not make sense to 
reference the same page from more than one navigation location "nav.adoc".  To make the "same" page available from several
navigation locations, use full content includes, one for each navigation location.  To make the situation completely symmetrical,
you may want to disable publication of the "original" by prefixing the file name with `_` or including the asciidoc attribute `:page-publishable: false`.
It is also possible to directly use the "original" in exactly one navigation location.

For instance...

`_popular.adoc`
```
= My Popular Page
:page-publishable: false

Popular content!
```
(This is redundant, using both the `_` prefix and the `:page-publishable: false` attribute)

`use1.adoc`
----
\include::./_popular.adoc[]
----

`use2.adoc`
----
\include::./_popular.adoc[]
----
...

`nav.adoc`
```
* Flow 1
** xref:use1.adoc[Popular 1]
* Flow 2
** xref:use2.adoc[Popular 2]
```

In (the likely) case that the uses are in different components, either the xref or include (or both) will need appropriate syntax
to identify the `_popular.adoc` page.