= Xref Pages in a Component Version
:xrefstyle: short
:listing-caption: Example

The majority of your cross references will probably be between pages that belong to the xref:ROOT:module-directories.adoc#module[same module] or to the xref:ROOT:component-version.adoc[same component version].

[#xref-page-in-module]
== Xref pages that belong to the same module

Only the xref:page-id.adoc#id-page[page coordinate] of the xref:page-id.adoc#target-page[target page] needs to be entered in the page ID when the xref:page-id.adoc#current-page[current page] and target page belong to the same component version and module.

[#ex-in-module-base]
.current-page.adoc
----
xref:target-page-filename.adoc[link text]
----

For context, let's use the pages that belong to the component version `colorado 5.2` as the basis for the examples on this page.
The component version's source files are stored in the xref:ROOT:standard-directories.adoc[set of standard directories] listed in <<ex-co>>.

[#ex-co]
.Standard directories assigned to the component version colorado 5.2
----
📒 repository
  📄 antora.yml
  📂 modules
    📂 get-started
      📂 pages
        📄 tour.adoc
    📂 la-garita
      📂 pages
        📄 cochetopa-pass.adoc
        📄 index.adoc
    📂 ROOT
      📂 pages
        📄 index.adoc
        📄 ranges.adoc
        📂 terms
          📄 faqs.adoc
----

The simplest xref is when the target and current pages belong to the same module.
<<ex-in-module>> shows an xref in the page [.path]_index.adoc_ (current page) that links to the [.path]_cochetopa-pass.adoc_ page (target page).
Both pages belong to the `la-garita` module.

[#ex-in-module]
.index.adoc (current page)
----
There are xref:cochetopa-pass.adoc[historic passes] in the range.
----

When the xref in <<ex-in-module>> is converted by Antora, it will become a link to the published site page at [.path]_\https://base-url.com/colorado/5.2/la-garita/cochetopa-pass.html_.

=== Xref pages in a topic folder

If the target page is nested in a topic folder, include the [.path]_pages_ family directory relative path in the page coordinate.
In <<ex-topic>>, an xref in the page [.path]_ranges.adoc_ (current page) links to the [.path]_faqs.adoc_ page (target page).
Both pages belong to the `ROOT` module, and [.path]_faqs.adoc_ is nested in the topic folder [.path]_terms_.

[#ex-topic]
.ranges.adoc (current page)
----
See the xref:terms/faqs.adoc[FAQs].
----

The xref in <<ex-topic>> will become a link to the published site page at [.path]_\https://base-url.com/colorado/5.2/terms/faqs.html_ when the site is generated.

[#xref-page-across-modules]
== Xref pages from other modules

The target page's xref:page-id.adoc#id-module[module coordinate] and page coordinate are required when the current and target pages belong to different modules.

[#ex-across-modules-base]
.current-page.adoc
----
xref:module:target-page-filename.adoc[link text]
----

The following examples use the pages that belong to the component version <<ex-co,colorado 5.2>>.
As seen in <<ex-across-modules>>, let's create an xref in the page [.path]_ranges.adoc_ (current page) that links to [.path]_cochetopa-pass.adoc_ (target page).
The _ranges.adoc_ page belongs to the `ROOT` module, while [.path]_cochetopa-pass.adoc_ belongs to the `la-garita` module.

[#ex-across-modules]
.ranges.adoc (current page)
----
Only xref:la-garita:cochetopa-pass.adoc[one pass is open] in the winter.
----

When published to a site, the current page will contain a link to the published target page's URL [.path]_\https://base-url.com/colorado/5.2/la-garita/cochetopa-pass.html_.

If the target page is nested in a topic folder, include the [.path]_pages_ family directory relative path as part of the page coordinate.
In <<ex-modules-topic>>, an xref in the page [.path]_tour.adoc_ (current page) links to the [.path]_faqs.adoc_ page (target page).
The page [.path]_tour.adoc_ belongs to the `get-started` module, and [.path]_faqs.adoc_ belongs to the `ROOT` module and is nested in the topic folder [.path]_terms_.

[#ex-modules-topic]
.tour.adoc (current page)
----
See the xref:ROOT:terms/faqs.adoc[FAQs].
----

== Learn more

To learn how to create xrefs to pages that belong to other components and component versions see xref:version-and-component-xrefs.adoc[Xref pages in other components and versions].
