= Create Page Links
//:page-aliases: version-and-component-xrefs.adoc
//module-and-page-xrefs.adoc,
//This page walks through examples demonstrating how to determine the resource IDs for the target and current pages and how to assign the correct sequence of coordinates to an xref macro to create a valid page link.
//* [x] how to assign the correct sequence of resource ID coordinates to an xref macro to create a valid page link
//* [x] how to determine the resource ID of the target page in relation to the current page when:

On this page, you'll learn how to assign the correct resource ID coordinates to an xref macro when:

* [x] <<xref-page-in-module>>: the target page and current page belong to the same component version and module
* [x] <<pages-root>>: the target page is stored at the root of the [.path]_pages_ directory
* [x] <<relative-path>>: the target page is stored in a subdirectory of the [.path]_pages_ directory
* [x] <<token>>: the target page and current page are stored in the same subdirectory of the [.path]_pages_ directory
* [x] <<xref-page-across-modules>>: the target page and current page belong to different modules
* [x] <<component-versions>>: the target page and current page belong to different component versions
* [x] the target page and current page don't belong to the same component version, and the page link should always use the latest version of the target page
* [x] the target page and current page belong to the same component, but they don't belong to the same version

[NOTE]
====
If you aren't familiar with the Antora resource ID, its coordinates, or how to use an xref macro, see:

* xref:resource-id.adoc[]
* xref:resource-id-coordinates.adoc[]
* xref:xref.adoc[]
====

[#xref-page-in-module]
== Page links within a module
//Link to a page in the same module
//Xref pages that belong to the same module

Most of the cross references you make will probably be between pages that belong to the xref:ROOT:module-directories.adoc#module[same module] in a component version.
The AsciiDoc xref macro only requires the xref:resource-id-coordinates.adoc#id-resource[file coordinate] of the target page's resource ID when the current page and target page belong to the same component version and module.

[TIP]
====
include::xref.adoc[tag=target-current-def]
====

<<ex-file-base>> shows the file coordinate of the target page assigned to an xref macro in the current page.

.current-page.adoc
[#ex-file-base]
----
xref:file-coordinate-of-target-page.adoc[optional link text] <.>
----
<.> The xref macro only needs to be assigned the file coordinate of the target page when the target page and current page belong to the same component version and module.
For general step-by-step instructions on how to set up an xref macro in a page, see xref:xref.adoc#make-link[Make a link with the xref macro].

The structure of the target page's file coordinate varies depending on whether the target page is stored at the root of the [.path]_pages_ family directory or in a subdirectory of the [.path]_pages_ directory.

.current-page.adoc
[#ex-file]
----
xref:target-page-filename.adoc[optional link text] <.>

xref:path/to/target-page-filename.adoc[optional link text] <.>

xref:./target-page-filename.adoc[optional link text] <.>

xref:target-page-filename.adoc#fragment[optional link text] <.>
----
<.> File coordinate of the target page when it's stored at the root of the [.path]_pages_ directory
<.> File coordinate of the target page when it's stored in a subdirectory of the [.path]_pages_ directory, but the current page isn't stored in the same subdirectory
<.> File coordinate of the target page when the target page and current page are stored in the same subdirectory of the [.path]_pages_ directory
<.> An optional fragment, representing an element ID in the target page, can be assigned after the target page's file coordinate

The following sections provide examples showing the different file coordinate structures.

[#pages-root]
=== File coordinate at pages directory root

When the target page is stored at the root of the [.path]_pages_ family directory, the file coordinate is the target page's filename and file extension.

.File coordinate in xref macro when target page is stored at root of pages directory
[#ex-page-base]
----
xref:target-page-filename.adoc[optional link text]
----

Let's use the pages that belong to the component version _colorado 5.2_ as the basis for the examples in this section.
The component version's source files are assigned to modules and families based on the xref:ROOT:standard-directories.adoc[set of standard directories] listed in <<ex-co>>.

.Directories assigned to the colorado 5.2 component version
[listing#ex-co]
----
📄 antora.yml <.>
📂 modules
  📂 la-garita <.>
    📂 pages <.>
      📄 willow-creek.adoc
      📄 ridge.adoc
  📂 ROOT <.>
    📂 pages <.>
      📄 index.adoc
      📄 ranges.adoc
----
<.> Defines the component version as _colorado 5.2_
<.> Defines a module named _la-garita_
<.> Defines subsequent files as pages
<.> Defines the _ROOT_ module
<.> Defines subsequent files as pages

Using the two pages that belong to the _la-garita_ module, shown in <<ex-co>> above, let's reference [.path]_willow-creek.adoc_ from [.path]_ridge.adoc_.
That means the source file [.path]_willow-creek.adoc_ is the target page and [.path]_ridge.adoc_ is the current page.
When the target page and current page belong to the same module, only the file coordinate of the target page's resource ID needs to be entered in the xref macro.
<<ex-page>> shows an xref macro in the [.path]_ridge.adoc_ page (current page) that links to the [.path]_willow-creek.adoc_ page (target page).

.ridge.adoc (current page)
[#ex-page]
----
The xref:willow-creek.adoc[trailhead] is north of town.
----

The file coordinate for the [.path]_willow-creek.adoc_ page consists solely of its filename and file extension, `willow-creek.adoc`, because it's stored at the root of the [.path]_pages_ directory.
The file coordinate of the target page is always calculated from the root of the [.path]_pages_ family directory.

Let's look at another xref macro, shown in <<ex-in-root>>, that references the [.path]_ranges.adoc_ page (target page) from the [.path]_index.adoc_ page (current page).

.index.adoc (current page)
[#ex-in-root]
----
The Rocky Mountains consists of xref:ranges.adoc[numerous mountain ranges].
----

Only the file coordinate of the target page needs to be specified in the xref macro because both pages belong to the _ROOT_ module.
The file coordinate for [.path]_ranges.adoc_ is `ranges.adoc` because it's stored at the root of the [.path]_pages_ directory.
If the target page is stored in a subdirectory of the [.path]_pages_ directory, its file coordinate must specify the [.path]__pages__-relative path or `./` token depending on its relation to the current page.
See <<relative-path>> and <<token>> for file coordinate examples when the target page is stored in a subdirectory.

[#relative-path]
=== File coordinate with pages-relative path
//Link to a page in a subdirectory

The __pages__-relative path of the <<target,target page>> is required in its file coordinate when the <<current,current page>> isn't stored in the same subdirectory as the target page.
If both pages are stored in the same subdirectory, see <<token>>.

.File coordinate in xref macro when target page is stored in subdirectory of pages directory
[#ex-subdir-base]
----
xref:path/to/target-page-filename.adoc[optional link text]
----

Let's use the pages that belong to the component version shown in <<ex-co-subdir>> as the basis for the examples in this section.

.Directories assigned to the colorado 5.2 component version
[listing#ex-co-subdir]
----
📄 antora.yml <.>
📂 modules
  📂 ROOT <.>
    📂 pages <.>
      📄 index.adoc
      📄 ranges.adoc
      📂 terms <.>
        📄 faq.adoc
        📄 signs.adoc
----
<.> Defines the component version as _colorado 5.2_
<.> Defines the _ROOT_ module
<.> Defines subsequent source files as pages
<.> A subdirectory in _pages_ containing the source files of pages

Let's reference [.path]_faq.adoc_ from [.path]_ranges.adoc_.
As you can see in <<ex-co-subdir>> above, both pages belong to the _ROOT_ module.
In <<ex-subdir>>, an xref macro in the [.path]_ranges.adoc_ page (current page) links to the [.path]_faq.adoc_ page (target page).

.ranges.adoc (current page)
[#ex-subdir]
----
See the xref:terms/faq.adoc[FAQs].
----

As shown in <<ex-subdir>>, the file coordinate for [.path]_faq.adoc_ is `terms/faq.adoc`.
The file coordinate for [.path]_faq.adoc_ consists of its [.path]__pages__-relative path, filename, and file extension because it's stored in the subdirectory [.path]_terms_ while the current page, [.path]_ranges.adoc_, is stored in the [.path]_pages_ directory.
If the current page and target page were stored in the same subdirectory, you could use the relative path token, `./`, in place of the __pages__-relative path.

[#token]
=== File coordinate with relative path token

If the <<target,target page>> and <<current,current page>> are stored in the same subdirectory within the [.path]_pages_ directory, the __pages__-relative path segment of the target page's file coordinate can be replaced with the relative path token, `./`.

.File coordinate in xref macro when target and current pages are stored in the same subdirectory
[#ex-token-base]
----
xref:./target-page-filename.adoc[optional link text]
----

Let's use the pages that belong to the component version shown in <<ex-co-token>> as the basis for the examples in this section.

.Directories assigned to the colorado 5.2 component version
[listing#ex-co-token]
----
📄 antora.yml
📂 modules
  📂 ROOT <.>
    📂 pages <.>
      📄 index.adoc
      📂 terms <.>
        📄 faq.adoc
        📄 signs.adoc
----
<.> Defines the _ROOT_ module
<.> Defines subsequent source files as pages
<.> A subdirectory in [.path]_pages_ containing the source files of pages

Let's reference [.path]_faq.adoc_ from [.path]_signs.adoc_.
<<ex-co-token>> shows that both files are stored in the [.path]_terms_ subdirectory of the [.path]_pages_ directory, and that both files belong to the _ROOT_ module of the same component version.
When the target page and current page are stored in the same subdirectory within the [.path]_pages_ directory, the relative path token, `./`, can be used to abbreviate the target page's file coordinate.
In <<ex-token>>, the xref macro in the [.path]_signs.adoc_ page (current page) links to the [.path]_faq.adoc_ page (target page).

.signs.adoc (current page)
[#ex-token]
----
See the xref:./faq.adoc[FAQs].
----

As shown in <<ex-token>>, the file coordinate for [.path]_faq.adoc_, when referenced from [.path]_signs.adoc_, is `./faq.adoc`.
Both pages are stored in the [.path]_terms_ subdirectory, therefore, the relative path segment of the target page's file coordinate is replaced with the `./` token.

[#xref-page-across-modules]
== Page links between modules

When the <<target,target page>> and <<current,current page>> don't belong to the same module, you must specify the target page's xref:resource-id-coordinates.adoc#id-module[module coordinate] and xref:resource-id-coordinates.adoc#id-resource[file coordinate] in the xref macro.

.Module and file coordinate in xref macro
[#ex-module-base]
----
xref:module:target-page-filename.adoc[optional link text] <.>

xref:module:path/to/target-page-filename.adoc[optional link text] <.>
----
<.> The xref macro is assigned the module coordinate and file coordinate of the target page when the target page and current page don't belong to the same module.
The target page's file coordinate is its filename and file extension when the target page is <<pages-root,stored at the root of a _pages_ family directory>>.
<.> If <<relative-path,the target page is stored in a subdirectory of a _pages_ directory>>, the target page's file coordinate must specify its __pages__-relative path, filename, and file extension.

Let's use the pages that belong to the component version shown in <<ex-co-mod>> as the basis for the examples in this section.

.Directories assigned to the colorado 5.2 component version
[listing#ex-co-mod]
----
📄 antora.yml <.>
📂 modules
  📂 la-garita <.>
    📂 pages <.>
      📄 willow-creek.adoc
  📂 ROOT <.>
    📂 pages <.>
      📄 index.adoc
      📄 ranges.adoc
----
<.> Defines the component version as _colorado 5.2_
<.> Defines a module named _la-garita_
<.> Defines subsequent files as pages
<.> Defines the _ROOT_ module
<.> Defines subsequent source files as pages

Using two pages from the _colorado 5.2_ component version, shown in <<ex-co-mod>> above, let's reference [.path]_ranges.adoc_ from [.path]_willow-creek.adoc_.
That means the source file [.path]_ranges.adoc_ is the target page and [.path]_willow-creek.adoc_ is the current page.
When the target page doesn't belong to the same module as the current page, the module coordinate and file coordinate of the target page's resource ID needs to be entered in the xref macro.

<<ex-module>> shows an xref macro in the page [.path]_willow-creek.adoc_ (current page) that links to [.path]_ranges.adoc_ (target page).
The [.path]_willow-creek.adoc_ page belongs to the _la-garita_ module, but _ranges.adoc_ belongs to the _ROOT_ module.

.willow-creek.adoc (current page)
[#ex-module]
----
Only xref:ROOT:ranges.adoc[one pass is open] in the winter.
----

As shown in <<ex-module>>, the target page's module coordinate is `ROOT` and its file coordinate is `.ranges.adoc`.

//[#xref-page-in-different-docs-component]
[#component-versions]
== Page links between component versions

When the <<target,current and target pages>> belong to different docs components, you must, at a minimum, specify the target page's xref:resource-id-coordinates.adoc#id-component[component, module, and file coordinates].
You'll almost always specify the version coordinate, too.

.current-page.adoc
[source#ex-component-version-base]
----
xref:version@component:module:target-page-file.adoc[link text]
----

For context, let's use the pages that belong to the component versions `colorado 5.2` and `wyoming 1.0` as the basis for the examples on this section.
Their source files are stored in the xref:ROOT:standard-directories.adoc[standard directory trees] listed in <<ex-co-and-wy>>.

.Standard directories assigned to the component versions colorado 5.2 and wyoming 1.0
[listing#ex-co-and-wy]
----
📒 repository
  📄 antora.yml <1>
  📂 modules
    📂 get-started
      📂 pages
        📄 tour.adoc
    📂 la-garita
      📂 pages
        📄 willow-creek.adoc
    📂 ROOT
      📂 pages
        📄 index.adoc
        📄 ranges.adoc

📒 repository
  📂 docs
    📄 antora.yml <2>
    📂 modules
      📂 sierra-madre
        📂 pages
          📄 elevation.adoc
          📄 wilderness-areas.adoc
----
<1> Declares files that belong to the colorado 5.2 component version
<2> Declares files that belong to the wyoming 1.0 component version

<<ex-across-components>> shows an xref in the page [.path]_index.adoc_ (current page) that links to the [.path]_elevation.adoc_ page (target page).
[.path]_index.adoc_ belongs to version `5.2` of the component `colorado`.
[.path]_elevation.adoc_ belongs to version `1.0` of the component `wyoming`.

.index.adoc (current page)
[source#ex-across-components]
----
See xref:1.0@wyoming:sierra-madre:elevation.adoc[How are peaks measured]?
----

When the xref in <<ex-across-components>> is converted, it will become a link to the published page at [.path]_\https://base-url.com/wyoming/1.0/sierra-madre/elevation.html_.

In <<ex-across-components-short-root>>, the page [.path]_ranges.adoc_ is referenced from the page [.path]_elevation.adoc_ (current page).
The target page, [.path]_ranges.adoc_, belongs to the `ROOT` module of the `colorado` component.

.elevation.adoc (current page)
[source#ex-across-components-short-root]
----
xref:5.2@colorado::ranges.adoc[List of ranges by height]
----

Notice in <<ex-across-components-short-root>> that the module name `ROOT` seems to be missing from the resource ID.
When a component coordinate is specified in a resource ID, and the target page belongs to the `ROOT` module, the module coordinate `ROOT` doesn't have to be explicitly specified.
But you must still enter the colon `:` that would follow the module coordinate.
You can see this `:` directly before the file coordinate `ranges.adoc`.
This shorthand only works when a component coordinate is specified and the module of the target page is `ROOT`.
In all other cases where the module coordinate is required, the name of the module must be specified.

[#xref-latest-version-of-component-version-page]
=== Xref the latest version of a page

TIP: This behavior only applies when the target and current pages belong to different docs components!

If a version isn't specified in the resource ID entered in the xref macro, *and the target and current pages belong to a different docs components*, Antora will use the xref:ROOT:how-component-versions-are-sorted.adoc#latest-version[latest version] of the target page's component to complete the resource ID.

Using the component versions previously described in <<ex-co-and-wy>>, let's create an xref in the page [.path]_index.adoc_ (current page) that links to the [.path]_elevation.adoc_ page (target page).
The xref is shown below in <<ex-across-components-latest>>.
[.path]_index.adoc_ belongs to version `5.2` of the component `colorado`.
[.path]_elevation.adoc_ belongs to version `1.0` of the component `wyoming`.
Notice that the target page's version coordinate isn't specified.

.index.adoc (current page)
[source#ex-across-components-latest]
----
See xref:wyoming:sierra-madre:elevation.adoc[How are peaks measured]?
----

Since there isn't a version coordinate in <<ex-across-components-latest>>, Antora will automatically complete the resource ID at runtime using the latest version -- `1.0` -- of the `wyoming` component.
When you release a newer version of `wyoming`, such as version `1.5`, and add it to your site, the xref in <<ex-across-components-latest>> will automatically link to the [.path]_elevation.adoc_ page in version `1.5` of `wyoming`.

WARNING: This behavior of linking to the latest version only applies when the version coordinate is unspecified and the target and current pages belong to different components.
If you don't specify a version and a component in the resource ID, Antora assumes the target page's version and component are the same as the current page's version and component coordinates.

[#xref-page-in-different-version]
== Xref pages from other versions

When the current and target pages belong to the same docs component, but the target page belongs to a different version of that component, you'll specify the version, module (if it's different), and file coordinates.

.current-page.adoc
[source#ex-version-module-base]
----
xref:version@module:target-page-filename.adoc[link text]
----

If the target and current pages belong to the same module, too, then you only need to specify the version and file coordinates of the target page.

.current-page.adoc
[source#ex-version-base]
----
xref:version@target-page-filename.adoc[link text]
----

For context, let's use the pages that belong to the component versions `colorado 5.2` and `colorado 6.0` as the basis for the example in this section.
Their source files are stored in the xref:ROOT:standard-directories.adoc[standard directory trees] listed in <<ex-co-versions>>.

.Standard directories assigned to the component versions colorado 5.2 and colorado 6.0
[listing#ex-co-versions]
----
📒 repository | branch name v5.2.x
  📄 antora.yml <- Declares files belong to colorado 5.2
  📂 modules
    📂 get-started
      📂 pages
        📄 tour.adoc
    📂 la-garita
      📂 pages
        📄 willow-creek.adoc
    📂 ROOT
      📂 pages
        📄 index.adoc
        📄 ranges.adoc

📒 repository | branch name v6.0.x
  📄 antora.yml <- Declares files belong to colorado 6.0
  📂 modules
    📂 la-garita
      📂 pages
        📄 willow-creek.adoc
    📂 ROOT
      📂 pages
        📄 index.adoc
        📄 ranges.adoc
----

Notice that the `colorado 5.2` component version has a [.path]_tour.adoc_ page that belongs to the `get-started` module.
However, `colorado 6.0` has no such module or page.

Let's reference the page [.path]_tour.adoc_ (target page), which belongs to `colorado 5.2`, from the page [.path]_willow-creek.adoc_ (current page), which belongs to the `colorado 6.0` component version.
In <<ex-across-versions>>, the xref specifies the target page's version, module, and file coordinates.

.willow-creek.adoc (current page) in colorado 6.0
[source#ex-across-versions]
----
Last year's xref:5.2@get-started:tour.adoc[excursions] were riveting!
----

When the xref in <<ex-across-versions>> is converted by Antora, it will become a link to the published site page at [.path]_\https://base-url.com/colorado/5.2/get-started/tour.html_.

[#default-link-text]
== Use the target page's default link text

When an xref doesn't specify any link text, Antora uses the target page's `reftext` value as the link text.
Let's create an xref to the [.path]_resource-id.adoc_ page in Antora's own documentation.

----
See xref:resource-id.adoc[].
----

Notice the xref doesn't have any link text specified.
As you can see in the example output below, Antora automatically fills in the link text using the title of the target page.

====
See xref:resource-id.adoc[].
====

If you click on the link, you'll see that the clickable text and the title of the target page are the same.
A page's title is assigned to the built-in AsciiDoc `reftext` attribute by default.
You can also xref:reftext-and-navtitle.adoc[assign a custom value to the reftext attribute].

CAUTION: When the resource ID of the target page is appended with a xref:xref.adoc#id-fragment[fragment (deep link)] and no link text is specified between the square brackets, like `\xref:page.adoc#fragment[]`, the link text isn't automatically populated.
You'll need to specify the link text in the xref macro when using a fragment.

TIP: Xrefs in a navigation file behave the same way with one additional feature.
Navigation files use the xref:reftext-and-navtitle.adoc#navtitle[navtitle value] to populate missing link text.
If `navtitle` isn't set, then they use the page's `reftext` value.

== Learn more

To learn how to create xrefs to pages that belong to other components and component versions see xref:version-and-component-xrefs.adoc[].
