= Page Attributes

Attributes that are prefixed with `page-` get promoted to the xref:antora-ui-default::templates.adoc#template-variables[UI model] that's used by the UI templates.
Certain page attributes, such as page-aliases and page-layout, are used to control built-in functionality in Antora.

== Define a built-in page attribute

Antora provides a few built-in page attributes that accept user-defined values, such as `page-aliases` and `page-layout`.
The attribute is set by entering its name in an xref:attributes.adoc#attribute-entry[attribute entry] in the header of the page.
The value you assign to the attribute must be offset from the closing colon (`:`) by at least one space.

[source]
----
= Page Title
:page-aliases: admin:forgot-password.adoc
----

The type of value a built-in page attribute accepts depends on the attribute.
For instance, the xref:page-aliases.adoc[page-aliases attribute] only accepts page IDs in a comma-separated list.

WARNING: Antora automatically sets a number of read-only page attributes at runtime that it derives from the playbook and component version descriptor keys.
The read-only page attribute names listed in the xref:ROOT:environment-and-page-attributes.adoc[Page and environment attribute reference] are reserved.
Don't unset or override them in the header of a page.

[#custom-attribute]
== Define a custom page attribute

You can also create custom page attributes, which can be accessed from the UI model via `page.attributes`.

Page attributes are defined just like any other AsciiDoc attribute, using an attribute entry.
Each page attribute must have a user-defined name prefixed with `page-`.
Like all AsciiDoc attributes, the name cannot contain dots (`.`) or blank spaces.
Custom `page-` attributes accept string values.

When a page attribute is promoted to the UI model, the `page-` prefix is removed.

Here's an example of a page that defines two page attributes.

[source]
----
= Page Title
:page-level: Intermediate
:page-team: SecOps
----

These attributes can be access from the UI model via the expression `page.attributes.level` and `page.attribues.team`.
