= Page ID

In order for a page to be linked to, i.e., referenced, that page must have an identifier--a page ID.
An [.term]*Antora page ID* is a unique and reliable set of identifying coordinates, organized in a standard order, that are constructed from the properties assigned to each page's source file.

[#structure]
== How is a page ID structured?

Antora constructs a page ID for a page source file from the key-value pairs specified in a xref:component-version-descriptor.adoc[component version descriptor] and the xref:ROOT:standard-directories.adoc[standard directory set].
Using this information, each page can be referenced using a unique and reliable set of page ID coordinates.

[#id-version]
Version::
The xref:ROOT:component-name-and-version.adoc#version-key[version of the component] to which the page belongs.

[#id-component]
Component::
The xref:ROOT:component-name-and-version.adoc#name-key[name of the component] to which the page belongs.

[#id-module]
Module::
The xref:ROOT:module-directories.adoc#module[module] in which the page is grouped.

Page::
The path to the xref:ROOT:pages-directory.adoc[page's source file] in the module, including any leading topic directories and the _.adoc_ file extension.

These coordinates are organize in a standard structure to create a unique, fully-qualified page ID.

image::page-id-anatomy-diagram.svg[Page ID anatomy,600]

For example, this is the fully-qualified page ID for the "`How Antora Works`" page, which belongs to the ROOT module of the {page-component-title} {page-component-version} component version.

[subs=attributes+]
----
{page-component-version}@antora:ROOT:how-antora-works.adoc
----

== How is a page referenced with its ID?

A page ID is used in an AsciiDoc cross reference, also called an xref, to link one documentation page to another documentation page.

image::xref-macro-anatomy-diagram.svg[Page reference anatomy,780]

Here's how that looks in practice:

[subs=attributes+]
----
Learn about xref:{page-component-version}@antora:ROOT:how-antora-works.adoc[the Antora pipeline].
----

Specifying the version, component name, and even module every time seems like overkill, right?
Don't worry, there's a shorthand.

For instance, if you're linking to a page in the same module as the page you're linking from, all you need to do is specify the `page` coordinate.
A whole range of examples, from linking between different components to linking to different versions of a page, are explained in xref:asciidoc:page-to-page-xref.adoc[page cross references].

[#important]
== Why are page IDs important?

*We've avoided coupling to the published URL* by using a source-to-source reference.
Notice the page coordinate ends with [.path]_.adoc_, the file extension of an AsciiDoc source file.
Regardless of whether you're deploying your site locally, to a staging or production environment, or you change URL strategies, the page ID always remains the same.
The cross reference locks on to the target page and produces a URL that points to it wherever it gets published.

*We've avoided coupling to the filesystem* by using an identifier based on the Antora's virtual component version classification system.

*We've eliminated the relative path (../../) problem* by specifying the page as a module-relative path.
The path always starts from a module's [.path]_pages_ directory, even when the referencing page is located inside a topic folder.
If you move or rename a page within a module, you don't have to change any references to other pages.

*This human-friendly referencing system saves you from having to do computations in your head while writing*.
You just specify the coordinates of the page you want to reference.
There's no need to worry about the source file's physical location on disk or its published URL.
All you need to know are the names of your components, versions, modules, and pages so you can fill in this information.

////
This needs to go in a section about future development.

Of course, inbound references to the page you move do have to be updated.
To counter this, you could pin the page ID of the page you want to move, thus adding more stability.
That way, references to the page don't have to be updated even when it moves.
Though, a little help from the text editor to "`refactor`" references could make this abstraction unnecessary.

*We've made it possible to validate and update references* by using a well-defined pattern that's easy for a script to locate, parse, and rewrite.
////
