= Partials
:page-aliases: partials-and-content-snippets.adoc, create-a-partial.adoc

== Reusable, single source content

Partials are good for storing snippets of content, such as common descriptions, project introductions, terminology, frequent admonitions, and reference tables, that you reuse in one or more pages throughout your site.
Partial files are stored in a xref:ROOT:partials-directory.adoc[_partials_ directory] and, regardless of which component version they belong to, can be referenced by any page or partial in your site.
A partial is referenced using its resource ID and the xref:include-a-partial.adoc[AsciiDoc include directive].
Select regions or lines from a partial, instead of all of the content in the partial, can be inserted into a page using the include directive's `tag`, `tags`, or `lines` attributes.
Changes you make to the partial will disseminate to all of the pages where you referenced it the next time you build your site.

== Create a partial file

Unlike a page, a partial doesn't have any required structural elements, such as a title, though it can contain such elements.
A partial is usually regular content marked up with AsciiDoc, but it isn't required that a partial be an AsciiDoc file or that it have a file extension.

=== Set up an AsciiDoc partial file

. Open a new file in your IDE or plain text editor.

. On the first line of the file, enter your content, such as paragraph text, a table, or an attribute entry.
In this example, let's create an admonition that's going to be used on several pages throughout a site.
+
----
[WARNING]
====
High, open places above the treeline are awe-inspiring--
but you need to be prepared for the altitude and
rapidly changing weather conditions.
====
----

. Once you finish creating your content, save the file with the extension `.adoc` in a [.path]_partials_ directory.
+
[listing]
----
📂 modules
  📂 ROOT
    📂 pages
      📄 a-source-file.adoc
    📂 partials
      📄 treeline-warning.adoc
----

You've created a partial!
Now, it's ready to be xref:include-a-partial.adoc[included in a page].

[#current-context]
== Current page context and structure

As you create the content in a partial, there are certain AsciiDoc elements that you may need to adjust according to the current page's context and structure.
A partial is converted after it's inserted into a page.
Therefore, the current page's component version, module, attributes, and other elements are applied to and may impact the included content.

=== Referencing pages and resources

Xrefs:: If the partial is included in pages that belong to other modules or docs components, you need to specify the resource IDs of the target resources in the partial's content accordingly.
The number of resource ID coordinates required depends on what component version and module the current page belongs to in relation to the target resource being referenced by the xref macro in the partial.

Images, examples, and other partials:: A partial can reference other partials and examples using the include directive and images using the image macros.
Like when entering resource IDs in xrefs, the resource ID of the target resource may need additional coordinates specified depending on the component version and module of the current page that partial is being included into and the resource being referenced in the partial.

=== Section headings

A partial can contain section headings.
You may need to use the `leveloffset` attribute to adjust the partial's heading levels, depending on where you enter the referencing include directive in a current page.

=== Inline, block, and section IDs

Element IDs in a partial can't conflict with the element IDs of the page into which it's being inserted.

=== Attributes

xref:attributes.adoc[Attributes] can be set, assigned, and referenced in a partial.
When an attribute is referenced in a partial, either the partial, current page, or current page's component version descriptor must set and assign a value to the attribute.

If an attribute is set and assigned a value in a partial, the attribute will be available in the current page starting from the point where the partial is included.
In such cases, the partial's attribute will override an attribute with the same name that is set or unset in the current page's header or soft set or unset from the current page's component version descriptor.
