= Resources and Resource IDs
:family: resource
:colon: :

No matter which component version or module a resource belongs to, it can be referenced by the other resources in your site using its resource ID and the applicable AsciiDoc syntax.

[#whats-a-resource-id]
== What's a resource ID?

A [.term]*resource* is a source file that is assigned to the attachments, examples, images, pages, or partials family.

An [.term]*Antora resource ID* is a unique and reliable set of identifying coordinates, organized in a standard sequence, that are constructed from the properties assigned to each resource's source file.
In Antora, a resource is referenced using its resource ID.

[#id-coordinates]
== What are the resource ID coordinates?

Antora constructs a resource ID for a source file from the key-value pairs specified in a xref:ROOT:component-version-descriptor.adoc[component version descriptor] and the xref:ROOT:standard-directories.adoc[standard directory set].
Using this information, a resource can be referenced from any other resource in your site using a unique and reliable set of resource ID coordinates.

A fully qualified resource ID with its coordinates organized in the standard sequence is shown below.

 version@component:module:family$resource.ext

include::partial$antora-id.adoc[tags=*;!page]

How many resource ID coordinates you need to specify when referencing a resource depends on the component version and module of the current page in relation to the target resource.

[[target-resource]]The [.term]*target resource* is the source file that will be linked to from the current page or embedded in the current page when the site is published.
[[current-page]]The [.term]*current page* is the page file that contains the AsciiDoc macro or include directive that references the target resource.

[#requires-family-coordinate]
== When is the family coordinate required?

The family coordinate doesn't always need to be specified in a resource ID.
It may be implicitly assigned by the AsciiDoc syntax you use to reference the resource.
For example, an image is always embedded in a page using an AsciiDoc image macro.
Since images are only referenced using the image macros, the `image$` coordinate is automatically applied to the target resource ID at runtime.

[#reference-syntax-id-requirements]
[cols="1,4,4,5"]
|===
|Resource |Referencing syntax |Example |Resource ID requirements

|xref:attachments.adoc[Attachment]
|Xref macro
|`+xref:attachment$brochure.pdf[]+`
|*The `attachment$` coordinate is required*.
See xref:attachments.adoc[].

|xref:examples-and-source-snippets.adoc[Example]
|Include directive
|`include::example$app.rb[]`
|*The `example$` coordinate is required*.
See xref:include-an-example.adoc[].

.2+|xref:images.adoc[Image]
|Block image macro
|`image::my-image.svg[]`
|No family coordinate required.
See xref:block-images.adoc[] and xref:image-resource-id-examples.adoc[].

|Inline image macro
|`+image:my-image.svg[]+`
|No family coordinate required.
See xref:inline-images.adoc[] and xref:image-resource-id-examples.adoc[].

.2+|xref:index.adoc[Page]
|Xref macro
|`+xref:the-steps.adoc[]+`
|No family coordinate required.

|Include directive
|`include::the-steps.adoc[tag=overview]`
|No family coordinate required.
See xref:include-a-page.adoc[].

|xref:partials-and-content-snippets.adoc[Partial]
|Include directive
|`include::partial$my-partial.adoc[]`
|*The `partial$` coordinate is required*.
See xref:include-a-partial.adoc[].
|===
