= Cross References
:page-aliases: page-id.adoc, asciidoc:page-to-page-xref.adoc
:colon: :
// page:page-id.adoc#whats-a-page-id == What's a page ID?
// page:page-id.adoc#important == Why are page IDs important?

[#whats-a-cross-reference]
== What's a cross reference?

You use a [.term]*cross reference* to indicate that a piece of information in one resource, such as a term, concept, image, etc., is related to information in another resource.
In Antora, cross references are almost always created using the AsciiDoc xref macro.
A cross reference indicates this relationship by referencing the related resource, that is, linking to the published resource.
The term cross reference is often abbreviated to *xref*.

[#xref-macro]
== AsciiDoc xref macro

An AsciiDoc xref macro is used to create a source-to-source cross reference from one publishable resource to another publishable resource.
The xref macro is also used to create the cross references to xref:navigation:xrefs-and-link-text.adoc[pages] and xref:navigation:reference-resources.adoc[attachments] in a component version's navigation files.

An xref macro and its value--a valid xref:resource-id.adoc[resource ID] specifying a publishable page, attachment, or, occasionally, an image--are converted to a link to the target resource's published URL.
[[target]]The [.term]*target resource* is the resource source file that's referenced, by specifying its resource ID, as the value in an xref macro.
[[current]]The [.term]*current page* is the page containing the xref macro that references the target resource.
//The xref macro accepts the resource ID of a publishable resource, that is, a page, attachment, or image.
//When Antora runs, an xref macro with a valid resource ID is converted into a link that a site visitor can follow in their browser to access the published resource.
How many resource ID coordinates you need to specify depends on the component version and module of the <<current,current page>> in relation to the <<target,target resource>> and the family to which the target resource belongs.

First, let's review the AsciiDoc xref macro syntax.

image::xref-macro-diagram.svg[Diagram of an AsciiDoc xref macro with an Antora resource ID,600]

xref{colon}::
The prefix of the AsciiDoc xref macro.

target resource ID:: The xref:resource-id-coordinates.adoc[resource ID coordinates] of the target resource relative to the current page.
If the target resource is in a subdirectory, the file coordinate of it resource ID must include that subdirectory, even if the current page is located in the same directory.
Alternatively, you can add `./` to the start of the file coordinate as a shorthand for the family-relative path of the target resource.
When the resource ID contains the module coordinate, and the module name ends with the name of a built-in macro (e.g., `monolink`), you may have to escape that portion of the name by prefixing it with a backslash (e.g., `mono\link`).
If the target resource is a page, the `page$` family coordinate doesn't need to be entered in the resource ID.
If the target resource is an attachment or an image, the `attachment$` or `image$` coordinate, respectively, is required.

[#id-fragment]
#fragment::
A fragment is optional and only applies when the target resource is a page.
A fragment is an element ID that links to a section, block, or inline location within the target page.
The fragment starts with the hash symbol (`#`).
A target page's `reftext` and `navtitle` aren't used as <<link-text,the default link text>> when a fragment is specified.

[#link-text]
[link text]::
When a visitor clicks on the link text that's displayed on the current page in the published site, they're directed to the target resource.
The link text is optional.
If no link text is specified in the xref macro's square brackets (`[]`), the xref:reftext-and-navtitle.adoc[reftext or navtitle of the target page is displayed] unless a <<id-fragment,fragment>> is appended to the end of the resource ID.

Here's how an xref macro with a xref:resource-id-coordinates.adoc#full-id[fully qualified resource ID] for a page looks in practice:

.current-page.adoc
[source]
----
See xref:2.5@hyper:admin:page$modes.adoc[].
----

Specifying the version, component, module, and family coordinates every time seems verbose, right?
Don't worry, the more related the <<current,current page>> and <<target,target resource>> are, the less coordinates you need to enter in the resource ID.
For instance, if the target resource and current page belong to the same component version and module, you can drop the version, component, and module coordinates from the resource ID.

.current-page.adoc
[source]
----
See xref:page$modes.adoc[].
----

Also, because the target resource is a page, the `page$` family coordinate can be dropped.

.current-page.adoc
[source]
----
See xref:modes.adoc[].
----

Antora automatically applies the `page$` family to a resource ID in an xref macro if the family coordinate isn't specified.
Therefore, even when the target resource and current page belong to different component versions or modules, as long as the target resource is a page, the family coordinate doesn't need to be specified in the resource ID.

.current-page.adoc
[source]
----
See xref:2.5@hyper:admin:modes.adoc[].
----

== More examples

xref:module-and-page-xrefs.adoc[] shows how to create xrefs to pages that belong to the same module or component version as the current page.

For xref examples where the target and current pages belong to different components or different versions of the same component, see xref:version-and-component-xrefs.adoc[].

xref:attachments.adoc[] shows how to create xrefs when the target resource is an attachment.
