= Checklists
:keywords: check list, tick, ballot, punch list, O mark, tally, X mark
:url-task: {url-asciidoc}/lists/checklist/

On this page, you'll learn:

* [x] How to mark up a checklist with AsciiDoc.
* [x] How to create an clickable checklist with AsciiDoc.

== Checklist syntax

Task lists are xref:ordered-and-unordered-lists.adoc#unordered[unordered lists] that have list items marked as checked or not checked.

Here’s an example:

.Checklist syntax
[#ex-checklist]
----
* [*] checked
* [x] also checked
* [ ] not checked
----

The result of <<ex-checklist>> is rendered below.

* [*] checked
* [x] also checked
* [ ] not checked

If you want to make the checkbox clickable, add the `interactive` option to the checklist, which is shown here using the shorthand syntax (`%`) for `options`.

.Interactive checklist syntax
[#ex-interactive]
----
[%interactive]
* [ ] Binge watch Death in Paradise
* [ ] Visit a tropical island
----

The result of <<ex-interactive>> is rendered below.
Go ahead, click a box.

[%interactive]
* [ ] Binge watch Death in Paradise
* [ ] Visit a tropical island

.*AsciiDoc and Asciidoctor resources*
* {url-task}[Checklists^]
