= Include a Page
// URLs
:url-adoc-manual: https://asciidoctor.org/docs/user-manual
:url-tags: {url-adoc-manual}/#by-tagged-regions
:url-leveloffset: {url-adoc-manual}/#include-partitioning

In Antora, the AsciiDoc include directive has been configured to include another page or portion of a page into the current page.
You can include a page from anywhere in the site, including pages from a different component version or module.

== AsciiDoc include directive

In the simplest form, the target can be a path relative to the current page:

----
\include::./relative-page-filename.adoc[<attrlist>]
----

The target can also be a the resource ID of a page.
The resource ID ranges in scope from a page in the current module:

----
\include::page$page-filename.adoc[<attrlist>]
----

To a page in a different component version:

----
\include::version@component:module:page-filename.adoc[<attrlist>]
----

Let's explore the syntax of the include directive in detail.

== Include a page using its resource ID

. On a new line, enter the name of the directive followed by two colons.
+
[subs=+quotes]
----
*include::*
----

. Next, enter the xref:page:resource-id.adoc[resource ID] of the target page in the target slot.
The resource ID must include the `page$` family coordinate since the include directive can also be used to include files from other families.
+
[subs=+quotes]
----
\include::**version@component:module:page$page-filename.adoc**[]
----

. Close the directive using a set of square brackets (`[]`).
+
[subs=+quotes]
----
\include::version@component:module:page$page-filename.adoc**[]**
----

. The brackets may contain an optional list of attributes.
Include attributes are entered as key-value pairs separated by commas.
+
--
[subs=+quotes]
----
\include::version@component:module:page$page-filename.adoc[**tag=definition**]
----

All the attributes (e.g., `lines`, `tags`, `leveloffset`, `indent`) on the include directive are supported.
--

Antora supports filtering the lines of an include file by either line numbers using the `lines` attribute or tags using the `tag` or `tags` attributes.
Filtering by line numbers takes precedence.
See https://asciidoctor.org/docs/user-manual/#include-partial[the Asciidoctor documentation] for full details of the `lines` and `tag` or `tags` syntax.

== Include a page using a relative path

. On a new line, enter the name of the directive followed by two colons.
+
[subs=+quotes]
----
*include::*
----

. Next, enter the relative path of the target page in the target slot.
A relative path include is resolved from the current page (not the root of the pages family).
The relative path must be prefixed with `./`.
+
--
[subs=+quotes]
----
\include::**./relative-page-filename.adoc**[]
----

CAUTION: You may find that the relative path works without this prefix, but that could change in the future.
--

. Close the directive using a set of square brackets (`[]`).
+
[subs=+quotes]
----
\include::./relative-page-filename.adoc**[]**
----

. The brackets may contain an optional list of attributes.
Include attributes are entered as key-value pairs separated by commas.
+
--
[subs=+quotes]
----
\include::./relative-page-filename.adoc[**tag=definition**]
----

All the attributes (e.g., `lines`, `tags`, `leveloffset`, `indent`) on the include directive are supported.
--

[#page-partial]
== page-partial attribute

As Antora processes each page, it converts the contents of the file from AsciiDoc to HTML.
(Within a component version, pages are typically processed in order by module and relative filename).
The conversion of the contents from AsciiDoc to HTML would normally impact the behavior of the include directive.
Specifically, a page that uses the include directive to include a page that has already been processed would see HTML instead of AsciiDoc.

To rectify this ordering problem, Antora can retain the AsciiDoc source until all pages have been converted.
This behavior is activated by setting the `page-partial` attribute in the document header of the page.
As of Antora 2.2, the `page-partial` attribute is (soft) set globally by default.
(Soft set means the it can still be overridden by the page).
So, really, you don't even have to think of it.
It will just work.

The downside of retaining the AsciiDoc source is that it _may_ increase the peak heap usage of Antora for very large sites by ~ 10%.
If that's a concern, you can revert to the previous "`a la carte`" behavior.
To revert to the previous behavior (prior to Antora 2.2), set the following property in the playbook file:

[source,yaml]
----
asciidoc:
  attributes:
    page-partial: false
----

The `page-partial` attribute will no longer be set globally.
Now you *must* set the `page-partial` attribute on any page you want to use in an include directive.
For example:

[source]
----
= Shared Page
:page-partial:

Page contents.
----

With the `page-partial` attribute set, you can safely refer to that page using the include directive:

[source]
----
\include:shared-page.adoc[]
----

Recall that the `page-partial` attribute in the included page instructs Antora to retain the AsciiDoc source until all pages have been converted.

== Learn more

* xref:include-partial.adoc[Include a partial]
* xref:include-example.adoc[Include an example]
* xref:page:page-id.adoc[Page IDs]
* xref:page:resource-id.adoc[Resource IDs]

.*Asciidoctor resources*
* {url-tags}[Select regions of content with tags^]
* {url-leveloffset}[Offset section headings with leveloffset^]
