= Ordered and Unordered Lists
:keywords: enumerated sequence, bullet points, bulleted list, ol, ul
:url-continuation: {url-asciidoc}/lists/continuation/
:url-ordered: {url-asciidoc}/lists/ordered/
:url-unordered: {url-asciidoc}/lists/unordered/

On this page, you'll learn:

* [x] How to mark up an ordered list with AsciiDoc.
* [x] How to mark up an unordered list with AsciiDoc.
* [x] How to add other AsciiDoc elements to a list item.
* [x] How to mix ordered and unordered items in the same list.

[#ordered]
== Ordered list syntax

Ordered lists are useful when you need to number list items.
First level list items are created with a single dot (a period) and nested items by using two or more dots in front of each the item.
The dot (or dots) is separated from the content of the list item by a single space.

.Ordered list with nested levels
----
. Step 1
. Step 2
.. Details
... Mini-details
.... Micro-details
..... We're really down in the weeds now.
.. More details
. Step 3
----

You can nest unordered lists to any depth.
A different numbering or lettering scheme (e.g., arabic, alpha, roman, etc) used to identify each nesting level.
However, the depth at which a unique scheme is applied depends on the stylesheet.
The scheme will fallback to the browser default (arabic numbering) beyond that depth.

. Step 1
. Step 2
.. Details
... Mini-details
.... Micro-details
..... We're really down in the weeds now.
.. More details
. Step 3

You can control the numbering scheme using the list style.

[lowergreek]
. alpha
. beta
. gamma

You can control the start value using the start attribute.

[start=4]
. Picking up where we left off.
. Add one more ingredient.
. Mix and serve!

[#unordered]
== Unordered list syntax

When your list doesn't need to be numbered, use an unordered list.
First level list items are marked using an asterisk (`+*+`) and nested items by two or more asterisk.

.Unordered list with nested levels
----
* Item A
* Item B
** Item B1
*** Details
**** More details
***** Details about the details
** Item B2
* Item C
----

You can nest unordered lists to any depth.
Unordered lists use a bullet or other illustrative marker in front of each list item to identify each nesting level.
However, the depth at which a unique marker is applied depends on the stylesheet.
The scheme will fallback to the browser default (a square bullet) beyond that depth.

* Item A
* Item B
** Item B1
*** Details
**** More details
***** Details about the details
** Item B2
* Item C

You'll use AsciiDoc's unordered list syntax to xref:navigation:files-and-lists.adoc[structure your site's navigation] as well.

[#complex]
== Complex ordered and unordered lists

List items can be any AsciiDoc element.
You can also mix ordered and unordered list items.
Let's look at an example that contains a variety of content and list item types.

//Don't replace the callouts in this block with <.> or remove source
[source]
....
* A list item can contain two or more paragraphs or blocks of content.
+ <1>
[source,yaml]
----
  artifacts:
    expire_in: 1 week
----
+ <1>
====
An example block
====

** A literal paragraph doesn't require a list continuation.

 $ antora antora-playbook.yml

* You can also mix list item types in the same list.
** Unordered list item
... Ordered list item
.... Another ordered list item
+ <1>
term:: A description list term and content.
....
<1> A [.term]*list continuation* is a plus symbol (`{plus}`) on a line by itself that is immediately adjacent to the block being attached.

To add additional paragraphs or blocks to a list item, you must attach them with a list continuation (`{plus}`).

Here's how the complex list above is rendered.

--
* A list item can contain two or more paragraphs or blocks of content.
+
[,yaml]
----
  artifacts:
    expire_in: 1 week
----
+
====
An example block
====

** A literal paragraph doesn't require a list continuation.

 $ antora antora-playbook.yml

* You can also mix list item types in the same list.
.. Ordered list item
*** Unordered list item
.... Another ordered list item
+
term:: A description list term and content.
--

Alternatively, when a list item contains multiple blocks, you can wrap them in a delimited open block (`+--+`).
Then you only need a single list continuation line to attach the open block to the list item.

//Don't replace the callouts in this block with <.> or remove source
.Use an open block instead of multiple list continuations
[source,line-comment=]
....
* A list item that includes several blocks wrapped in an open block.
+ <1>
-- <2>
[source,yaml]
----
  artifacts:
    expire_in: 1 week
----

====
An example block
====

Another paragraph
-- <2>
....
<1> Single list continuation attaching the open block to the list item.
<2> Open block delimiters wrapping multiple blocks.

Here's how that example looks when rendered.

* A list item that includes several blocks wrapped in an open block.
+
--
[,yaml]
----
  artifacts:
    expire_in: 1 week
----

====
An example block
====

Another paragraph
--

You can find xref:description-lists.adoc#complex[another complex list example] on the description list page.

.*AsciiDoc and Asciidoctor resources*
* {url-ordered}[Basic and complex ordered lists^]
* {url-unordered}[Basic and complex unordered lists^]
* {url-continuation}[List continuation^]
