= Section Headings
:url-sections: {url-asciidoc}/sections/titles-and-levels/

On this page, you'll learn:

* [x] How to mark up section headings with AsciiDoc.

== Heading level syntax

Sections partition a page into a content hierarchy.
In AsciiDoc, sections are defined using section titles.

.Section title syntax
----
== Level 1 Section Title

=== Level 2 Section Title

==== Level 3 Section Title

===== Level 4 Section Title

====== Level 5 Section Title

== Another Level 1 Section Title
----

When a page is converted to HTML, each section title becomes a heading element where the heading level matches the number of equals signs.
For example, a level 1 section (`==`) maps to an `<h2>` HTML tag.

Section headings must be defined using the Atx-style (single line) that begins with one or more equals signs.
Antora does not recognize the legacy Setext-style (two line) syntax once supported by AsciiDoc.
If you use the Setext-style syntax, xrefs in the page will not be resolved and other features of AsciiDoc will not be available.

.*AsciiDoc and Asciidoctor resources*
* {url-sections}[Section titles^]
