= User Interface Macros

On this page, you'll learn:

* [x] How to mark up a button (press btn:[Submit]) with AsciiDoc.
* [x] How to mark up a keybindings (kbd:[Ctrl+Shift+N]) with AsciiDoc.
* [x] How to mark up a menu (menu:View[Zoom > Reset]) with AsciiDoc.

== Set the experimental attribute

The attribute `experimental` must be set as a xref:page:define-and-modify-attributes.adoc[page attribute], xref:ROOT:component-attributes.adoc[component version attribute], or xref:playbook:asciidoc-attributes.adoc[site attribute] to enable the UI macros styles in the reference UI.

[#button]
== Button syntax

Communicate that a user should press a button with the button macro.

.Button UI macro
[#ex-btn]
----
Press the btn:[Submit] button when you are finished the survey.

Select a file in the file navigator and click btn:[Open].
----

The result of <<ex-btn>> is displayed below.

====
Press the btn:[Submit] button when you are finished the survey.

Select a file in the file navigator and click btn:[Open].
====

[#keybinding]
== Keybinding syntax

Create keyboard shortcuts with the keybinding macro.

.Keybinding UI macro
[#ex-kbd]
----
Press kbd:[esc] to exit insert mode.

Use the shortcut kbd:[Ctrl+T] to open a new tab in your browser.

kbd:[Ctrl+Shift+N] will open a new incognito window.
----

The result of <<ex-kbd>> is displayed below.

====
Press kbd:[esc] to exit insert mode.

Use the shortcut kbd:[Ctrl+T] to open a new tab in your browser.

kbd:[Ctrl+Shift+N] will open a new incognito window.
====

[#menu]
== Menu syntax

Show readers how to select a menu item with the menu macro.

.Menu UI macro
[#ex-menu]
----
To save the file, select menu:File[Save].

Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.
----

The result of <<ex-menu>> is displayed below.

====
To save the file, select menu:File[Save].

Select menu:View[Zoom > Reset] to reset the zoom level to the default setting.
====
