= Get Help
// URLs
:url-issues: {url-repo}/issues
:url-twitter: https://twitter.com/antoraproject
:url-twitter-hash: https://twitter.com/hashtag/antora?src=hash
:url-contributing: https://gitlab.com/antora/antora/blob/main/contributing.adoc

Antora is designed to help you write and publish your documentation.
However, we can't fully realize this goal without your feedback!
We encourage you to report issues, ask questions, share ideas, or discuss other aspects of this project using the communication channels provided below.

== Chat

*The project chat is the preferred means of communication for all Antora users.*
This policy helps keep the project sustainable.
If you want to ask for help, share feedback, or exchange ideas with project maintainers and fellow community members in real time, please join us in the project chat.

* {url-chat}[Chat^] (Zulip)

The chat is partitioned into streams.
If you find an active discussion that matches the topic of your post, feel free to join that discussion.
Otherwise, please select a stream most relevant to your topic, click "`New Topic`", enter a subject, then write your post.
Please do not post unrelated questions or comments to an existing topic since that disrupts the discussion and makes answers more difficult to find.
If you aren't sure where to post, please create a new topic in the `#users` stream and a moderator may choose to reclassify it.

TIP: Please use the filter or search feature to find existing topics before starting a new one.

The discussions in the project chat are archived and public.
There's no guarantee those logs will be saved indefinitely, though we plan keep them as long as we're permitted to do so.

Keep in mind that users participate in the project chat voluntarily, so please be respectful of their time and interests.
The project chat is not 1-on-1 support.
You are in a public forum.

Do not `@` mention someone when writing a message unless a) the subject matter absolutely requires the attention of that person or b) that person has already replied to the topic and is interacting with you.
Using the `@` mention to draw attention to your question is not courteous to that person or fair to others.
You're free to post your message to the community at large (no `@` mention).
If someone has something to share in response, they will do so if and when they have time.
You can reference someone without notifying them using the `@_` prefix, which is considered acceptable conduct.

== Issues

The issue tracker is used to track changes to the software and for planning releases.
The issue tracker is not a support portal.
Instead, the issue tracker is reserved for reporting problems (verifiable bugs, regressions, and security vulnerabilities) and requesting new features.
If you aren't confident that a change to the software is required, please post to the <<Chat>> instead.

* {url-issues}[Issue tracker^] (GitLab)

Any significant change to the software or decision about the project must be logged in the issue tracker.

== Twitter

If you want to share your experience with Antora or help promote it, we encourage you to post about it on social media.
When you talk about Antora on Twitter, you can mention the official account for the project:

* {url-twitter}[@antoraproject^] -- The official Antora account on Twitter.

You can also use the {url-twitter-hash}[#antora^] hashtag to promote the project or discover other people talking about it.

== Code and content contributions

If you're interested in helping the maintainers improve the project, then check out the {url-contributing}[Antora contributing guidelines^].
