= Get Help
// URLs
:url-issues: {url-repo}/issues
:url-twitter: https://twitter.com/antoraproject
:url-twitter-hash: https://twitter.com/hashtag/antora?src=hash
:url-contributing: https://gitlab.com/antora/antora/blob/main/contributing.adoc

Antora is designed to help you write and publish your documentation.
However, we can't fully realize this goal without your feedback!
We encourage you to report issues, ask questions, share ideas, or discuss other aspects of this project using the communication channels provided below.

== Chat

*The project chat is the preferred means of communication for all users of Antora.*
This policy helps keep the project sustainable.

If you want to ask for help, share feedback, or exchange ideas with project maintainers and fellow community members in real time, please join us in the project chat.

* {url-chat}[Chat^] (Zulip)

The chat is partitioned into channels by subject matter.
This partitioning helps to keep conversations organized and makes it possible to filter topics to follow.
When you first join, spend a few minutes to get familiar with where topics are being discussed.

IMPORTANT: Please do not send direct messages to the maintainers asking for help with Antora.
The project maintainers do not provide 1-on-1 support.
All support should be done in the public channels, most often the `#users` channel.
Direct messages should only be used for personal matters.

Before starting a new topic, use the filter or search feature to look for existing topics before starting a new one.
You may find the information you're seeking within the discussions that have already taken place.
If you find an ongoing (i.e., unresolved) discussion that matches the topic of your post, feel free to join in that discussion.

If you can't find an existing topic that answers your question, or it's already been marked as resolved, you can start a new topic.
We ask that you select an appropriate channel before you create a new topic.
If you aren't sure where to post, create a new topic in the `#users` channel and a moderator will reclassify it if necessary.
No action is needed on your part.

Once you've selected a channel, click "`New Topic`", enter a subject, write your post, then click "`Send`".
You can also select a channel after you click "`New Topic`".

The discussions in the project chat are archived and public.
There's no guarantee the logs will be saved indefinitely, though we do plan keep them as long as we're permitted to do so.

The project chat is not 1-on-1 support.
You're in a public space.
Users participate in the project chat voluntarily.
Please be respectful of their time and interests.

IMPORTANT: Do not `@` mention someone when writing a message unless a) the subject matter absolutely requires the attention of that person or b) that person has already replied to the topic and is interacting with you.
Using the `@` mention to draw attention to your question is not courteous to that person or fair to others participating.
You're free to post your message to the community at large (no `@` mention).
If someone has something to share in response, they will do so if and when they have time.
You can reference someone without notifying them using the `@_` prefix, which is considered acceptable conduct.

== Issues

The issue tracker is used to track changes to the software and for planning releases.
The issue tracker is not a support portal.
Instead, the issue tracker is reserved for reporting problems (verifiable bugs, regressions, and security vulnerabilities) and requesting new features.
If you aren't confident that a change to the software is required, please post to the <<Chat>> instead.

* {url-issues}[Issue tracker^] (GitLab)

Any significant change to the software or decision about the project must be logged in the issue tracker.

== Twitter

If you want to share your experience with Antora or help promote it, we encourage you to post about it on social media.
When you talk about Antora on Twitter, you can mention the official account for the project:

* {url-twitter}[@antoraproject^] -- The official Antora account on Twitter.

You can also use the {url-twitter-hash}[#antora^] hashtag to promote the project or discover other people talking about it.

== Code and content contributions

If you're interested in helping the maintainers improve the project, then check out the {url-contributing}[Antora contributing guidelines^].
