= Get Help
// URLs
:url-issues: {url-repo}/issues
:url-twitter: https://twitter.com/antoraproject
:url-twitter-hash: https://twitter.com/hashtag/antora?src=hash
:url-contributing: https://gitlab.com/antora/antora/blob/main/contributing.adoc

Antora is designed to help you write and publish your documentation.
However, we can't fully realize this goal without your feedback!
We encourage you to report issues, ask questions, share ideas, or discuss other aspects of this project using the communication channels provided below.

== Chat

If you want to ask for help, share feedback, or exchange ideas with fellow community members in real time, please join the project chat.
The project chat is the preferred means of communication for all Antora users.

* {url-chat}[Chat^] (Zulip)

If you find an ongoing discussion that matches the topic of your post, feel free to join that discussion.
Otherwise, please post a new topic in the `#users` stream.
Only post to a different stream if you understand the stream's purpose and have determined that your topic is suitable for it.

The discussions in the project chat are archived, but there's no guarantee those logs will be saved indefinitely.
Keep in mind that users participate in the project chat voluntarily, so please respect their time.

== Issues

The preferred means of reporting verifiable bugs, regressions, and security vulnerabilities or for making formal change requests is the project issue tracker.

* {url-issues}[Issue tracker^] (GitLab)

Any significant change or decision about the project is recorded in the issue tracker.
The issue tracker is also used for planning releases.

== Twitter

If you want to share your experience with Antora or help promote it, we encourage you to post about it on social media.
When you talk about Antora on Twitter, you can mention the official account for the project:

* {url-twitter}[@antoraproject^] -- The official Antora account on Twitter.

You can also use the {url-twitter-hash}[#antora^] hashtag to promote the project or discover other people talking about it.

== Code and content contributions

If you're interested in helping the maintainers improve the project, then check out the {url-contributing}[Antora contributing guidelines^].
