= Land Acknowledgement

== Our Statement

We would like to acknowledge that the Antora project is primarily developed on land that occupies the traditional and unceded territories (Treaty of Fort Laramie: 1851 & 1868, Cession 426) of the Cheyenne, Očhéthi Šakówiŋ, and Ute Peoples, who have stewarded the land and its water for generations.

In offering this Land Acknowledgment, we affirm Indigenous sovereignty, history, and experiences.
May this acknowledgment express our commitment to listen to and honor the teachings of past and present Indigenous Peoples and to uphold their sacred relation to this land and water by helping to protect it.

== What is a Land Acknowledgment?

A Land Acknowledgment is a formal statement that gives thanks and gratitude to the Indigenous Peoples who worked and lived on the land in which we reside both presently and historically.
These statements honor Indigenous culture, their ancestral homelands, and the sacredness of land while recognizing the complex, ongoing history of colonialism, and the privilege we have to live where we do.

You can learn more about the history of the Indigenous lands in the United States and Canada, and why acknowledging that history matters, at https://native-land.ca/resources/territory-acknowledgement/[Native Land Digital^].
